### ISSUE TITLE
Pyinstaller with yfinance-moduel / Error "frozen importlib._bootstrap"?

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#1266]
Hello - after upgrading to version 0.2.3. of yfinance it seems that i am not able anymore to create a running exe-file using pyinstaller -
The python-file using yfinance is working fine - but when i try to create a executable file with pyinstaller eg. with

`pyinstaller --onefile stockma3.py>`

and then run the program i allways get this error:

```
G:\DEV\Fiverr\ORDER\VanaromHuot>stockma3.exe
Traceback (most recent call last):
  File "StockMA3.py", line 5, in <module>
    import StockCrawler as yc
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "StockCrawler.py", line 44, in <module>
    import yfinance as yf
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yfinance\__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yfinance\ticker.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yfinance\base.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yfinance\data.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "frozendict\__init__.py", line 33, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\marku\\AppData\\Local\\Temp\\_MEI63882\\frozendict\\VERSION'
[18860] Failed to execute script 'StockMA3' due to unhandled exception!

```

I also tried the exe-creation with the additonal parameters

`--hidden-import yfinance`

or

`--collect-datas=yfinance`

but in both cases i get the same error message?

Is there anything i can do to get a working executeable again?

**Comment by Rapid1898-code** [comment]
Hello - i was able to fix this issue using:

`pyinstaller --onefile --collect-data frozendict stockma3.py`

**Comment by tkarljws** [comment]
I know this is closed as completed, but I wanted to know if this issue is due to a bug within the yfinance package or an issue on my machine? Sorry if it's out of line to ask a question like this on a closed issue; I'm very green and still learning what's appropriate in cases like these.
