### ISSUE TITLE
Integrity Error when reading prices?

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#1321]
Hello - i create a simply test-program with output the prices for AAPL - 

```
from datetime import datetime, timedelta
import yfinance as yf
import time

tday = datetime.today()    
startDay = tday - timedelta(days=600)          
dfPrice = yf.download("AAPL", start=startDay, end=tday)   

print(dfPrice)
time.sleep(10)
```

Everything works fine - also when i bundle this to an exeduteable for windows.
But when i provide the exe-file to another user he gets on his computer this error:

```
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AAPL: IntegrityError('NOT NULL constraint failed: kv.key')
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

It seems that this is an yfinance-error and has nothing to do with the pyinstaller-bundeling.
What does this error message mean?
Why is it only happening on one computer and i am not able to reproduce this on mine?

**Comment by ValueRaider** [comment]
> Why is it only happening on one computer and i am not able to reproduce this on mine?

Because `yfinance` now stores exchange timezone info in your local cache, to speedup datetime localization. Sounds like your local timezone cache is bad. Also makes debugging tricky.

Can you try git branch `hotfix/sql-exception`? It has a potential fix but only you can test. Then after, run this because I'm curious:
```
yf.utils.get_tz_cache().tz_db.print()
```

**Comment by Rapid1898-code** [comment]
Thanks - how can i pip install the hotfix for the branch you mentioned?

**Comment by ValueRaider** [comment]
I don't know, I just run the git branch directly. If you find out, document in #1080 and I'll adjust the title.

**Comment by Rapid1898-code** [comment]
One additional questions cause you stated this:
`Because yfinance now stores exchange timezone info in your local cache, to speedup datetime localization. Sounds like your local timezone cache is bad.`

Is it also possible somehow to fix this bad local timezone cache on the pc?

**Comment by ValueRaider** [comment]
"bad" was an exaggeration on my part, it's really just a lack of internal checks that branch should fix. Probably `yfinance` is trying to set timezone=None (I'd like to know why because shouldn't happen), or a None has somehow entered cache database.

**Comment by Rapid1898-code** [comment]
Hello - i tried to use the branch - installing and running on my pc using python is no problem
(but as i mentioned initisally i have generally no problem using the actual yfinance version)

So i tried to bundle this to an executeable using:
`pyinstaller --onefile --collect-data G:\DEV\Fiverr\ORDER\ericromelczyk\yfinance test.py`
(the path is where i installed the branch-version)

But when i now run the executable on my computer i get this error:
```
G:\DEV\Fiverr\ORDER\ericromelczyk\yfinance
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    dfPrice = yf.download("AAPL", start=startDay, end=tday)
AttributeError: module 'yfinance' has no attribute 'download'
[33472] Failed to execute script 'test' due to unhandled exception!
```

How can i bundle the program with the yfinance-branch to an executable so i can test this on the other computer where the problems occurs?

**Comment by ValueRaider** [comment]
No idea. I just run the git branch directly. See #1080

**Comment by Rapid1898-code** [comment]
Hello - can you give me the full patch to the branch?

like:
`pip install git+https://github.com/tangentlabs/django-oscar-paypal.git@issue/34/oscar-0.6`
(i was told that i simply should install the branch in my virtual enironment using pip install)

**Comment by ValueRaider** [comment]
https://github.com/ranaroussi/yfinance/issues/1321#issuecomment-1399003709

**Comment by Rapid1898-code** [comment]
Hello - after running the program with you branch i get the following error:

Programm:
```
from datetime import datetime, timedelta
import time
import os
import sys

tday = datetime.today()    
startDay = tday - timedelta(days=600)          
dfPrice = yf.download("AAPL", start=startDay, end=tday)   
print(dfPrice)
time.sleep(10)
```

Error:
```
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AAPL: TypeError("bad operand type for unary ~: 'str'")
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

**Comment by ValueRaider** [comment]
Use `Ticker.history` instead, it should print the traceback:
```
yf.Ticker("AAPL").history(start=startDay, end=tday)
```

**Comment by Rapid1898-code** [comment]
Hello - this is the error my client get on his computer when he runs the executeable on windows i created - 
(as i said on my computer i don´t have this problems)

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
  File "yfinance\base.py", line 138, in history
  File "yfinance\base.py", line 803, in _get_ticker_tz
  File "yfinance\utils.py", line 860, in get_tz_cache
  File "yfinance\utils.py", line 779, in __init__
  File "yfinance\utils.py", line 825, in _migrate_cache_tkr_tz
  File "pandas\core\generic.py", line 1522, in __invert__
  File "pandas\core\internals\managers.py", line 350, in apply
  File "pandas\core\internals\blocks.py", line 351, in apply
TypeError: bad operand type for unary ~: 'str'
[20232] Failed to execute script 'test' due to unhandled exception!
```

**Comment by ValueRaider** [comment]
Error caused by a change in branch, now fixed. Try again.

**Comment by Rapid1898-code** [comment]
ok thanks - i will check it
btw: with this command i can pip install your branch:
`pip install git+https://github.com/ranaroussi/yfinance.git@hotfix/sql-exception`
(i was told in the pyinstaller forum - cause i need that to create an executable for my client)

**Comment by ValueRaider** [comment]
Thanks, I've updated #1080

**Comment by RobinDeeCee** [comment]
@ValueRaider Hey,

I still have the same problem here, not on mine first pc but on mine second one.
I did try branch hotfix/sql-exception but because this is still in v. 0.24 It has other issues (is it possible to merge this with the master so it fix the #1329 issue / will this still fix the issue)

What seems to work as a temp fix is setting up the tz_cache_location hardcoded (but I still need to test that more) => yf.set_tz_cache_location("America/New_York")

If you need more info about this topic, I'm open to cooperate to fix this.

I'm using:
* Python 3.11.1
* Ubuntu 20.04.3

**Comment by ValueRaider** [comment]
Price data should not have been affected by #1329 , and this sql error only affects price data. Anyway I've updated the branch.

**Comment by RobinDeeCee** [comment]
no no, But I also use the balance sheet, income statement,... Thats why it wasn't possible for me to use that branch in production.
however thanks for the dump. Sadly It still doesn't do the fix for me... I'm aware that you can't reproduce it so I will do some research myself, I will let you know (create PR) If I found any possible bugs.

Thanks anyway for all the work!

**Comment by ValueRaider** [comment]
> still doesn't do the fix for me

Ok then post details. Exception, stack trace, etc.
