### ISSUE TITLE
get_earnings raises type error

### ISSUE THREAD

**Issue by lucas03** [ranaroussi/yfinance#1327]
### Are you up-to-date?

yes

### Does Yahoo actually have the data?

No

### Are you spamming Yahoo?

No

### Still think it's a bug?

Delete this default message and submit your bug report here, providing the following as best you can:

- Simple code that reproduces your problem

```
    ticker = yfinance.Ticker('GLPG.AS')
    earnings = ticker.get_earnings(freq="quarterly", as_dict=True)
    print(earnings)
```

- The error message

```
Traceback (most recent call last):
  File "/Users/lukasvojt/Project/digrin/test/test.py", line 48, in <module>
    earnings = ticker.get_earnings(freq="quarterly", as_dict=True)
  File "/Users/lukasvojt/Project/digrin/env/lib/python3.9/site-packages/yfinance/base.py", line 964, in get_earnings
    dict_data['financialCurrency'] = 'USD' if 'financialCurrency' not in self._earnings else self._earnings[
TypeError: argument of type 'NoneType' is not iterable
```

I guess `self._earnings` is not expected to be None by this code?

**Comment by lucas03** [comment]
maybe just replace `self._earnings` with `self._fundamentals.earnings`?

**Comment by suhaskashyaps** [comment]
While using the stock.info['financialCurrency'] command, I am getting this error: KeyError: 'financialCurrency'
Has finance changed its structure? 
PS: I used this same command a few months back and it was working just fine.

**Comment by ValueRaider** [comment]
@lucas03 Maybe submit a pull request?

@suhaskashyaps You're issue is different, you should submit a new Issue. But first double-check bug because I can't reproduce.

**Comment by lucas03** [comment]
As I am not familiar with yfinance, I thought somebody would just say my random suggestion won't work because of ... I'll try pull request if I get some time for it 👍

**Comment by ValueRaider** [comment]
Seems everyone thinks that.

Check out #1084 first.

**Comment by ValueRaider** [comment]
You're thinking right area. But I'd question why it's trying to add currency in first place - inspect GitHub blame.
