### ISSUE TITLE
yahoo stores decryption is broken again

### ISSUE THREAD

**Issue by Rogach** [ranaroussi/yfinance#1334]
### Simple code that reproduces your problem

```
stock = yf.Ticker("^GSPC")
info = stock.info
```

### Error

```
Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption: '8859304c7f55'-><class 'str'> , '8859304c7f55'-><class 'str'> , '8859304c7f55'-><class 'str'> , '8859304c7f55'-><class 'str'> , '8859304c7f55'-><class 'str'> , '885930...
```

(note that I truncated the error message, due to a bug in error formatting code the message is quite long)

### Info about your system:

yfinance version: 0.2.4

**Comment by onesoned** [comment]
ticker = "msft"

import yfinance as yf
tickerYF = yf.Ticker(ticker)
print(tickerYF.info)

Traceback (most recent call last):
  File "C:\Users\**\source\repos\2021_12_15 Google API Python\2022_03_09 API\tester.py\00 yahooFinance tester.py", line 49, in <module>
    print(tickerYF.info)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "C:\Program Files\Python37\lib\site-packages\yfinance\base.py", line 895, in get_info
    data = self._quote.info
  File "C:\Program Files\Python37\lib\site-packages\yfinance\scrapers\quote.py", line 27, in info
    self._scrape(self.proxy)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\scrapers\quote.py", line 56, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 202, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 73, in decrypt_cryptojs_aes_stores
    raise Exception(msg)

**Comment by lucas03** [comment]
duplicate issue https://github.com/ranaroussi/yfinance/issues/1329

**Comment by Rogach** [comment]
You are right, I somehow missed that issue when posting mine.
