### ISSUE TITLE
Stock.info V0.26 Not working - failed to decrypt

### ISSUE THREAD

**Issue by Lad00dle** [ranaroussi/yfinance#1350]
Hi
First at all thanks for a nice liberay. 
Im having problem with runing the simple code

obj = yf.Ticker("AAPL")
info = obj.info
print(info)

debug code
..............................................

Traceback (most recent call last):
  File "C:\Users\User\Documents\Assets manage\Python\yfinance_test.py", line 10, in <module>
    info = obj.info
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\ticker.py", line 142, in info
    return self.get_info()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\base.py", line 1220, in get_info
    data = self._quote.info
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\scrapers\quote.py", line 96, in info
    self._scrape(self.proxy)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\scrapers\quote.py", line 125, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\data.py", line 256, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\data.py", line 190, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

Thanks 
Lad00dle

**Comment by tomekkurzydlak** [comment]
Same for me. Yesterday's hotfix worked fine, but now this exception is raised while getting:
coin = yf.Ticker(ticker)
price = coin.info['regularMarketPrice'] 
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

**Comment by ovdavid28** [comment]
Same issue here since two days ago.
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

**Comment by 0zd3m1r** [comment]
same issue: https://github.com/ranaroussi/yfinance/issues/1349

**Comment by avdrav1** [comment]
Same for me

**Comment by vasiaplaton** [comment]
Absolutely the same for me, works fine yesterday, but for now 
`Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

**Comment by basgir** [comment]
Same

**Comment by galashour** [comment]
Friends - this is a widespread issue, that is being looked at. 
I think there is little value if each of us will just confirm that.

In order to minimize distractions to the developers (and others who are tracking progress), I suggest that instead of adding a comment just for acknowledging the problem - to consider switching the 'watching' setting (for a short while) at the top of the page to 'all activity' (again, for a short while, hopefully a couple of days), and once a solution is found a message will be sent to all 'subscribed/watching' (and then we can set the 'watching' level back to the 'mentions / participating'  

Thanks
