### ISSUE TITLE
Failed to decrypt data, hardcoded keys.

### ISSUE THREAD

**Issue by RuimanDiaz** [ranaroussi/yfinance#1352]
I have an issue with yfinance. This is the code:
```
import yfinance as yf

apple = yf.Ticket('AAPL')

apple.info
```
and the output is:
```
Exception                                 Traceback (most recent call last)
[<ipython-input-28-232e42d65d3e>](https://a5ze5evp5uh-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230124-060109-RC00_504221406#) in <module>
----> 1 apple.info

6 frames
[/usr/local/lib/python3.8/dist-packages/yfinance/data.py](https://a5ze5evp5uh-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230124-060109-RC00_504221406#) in decrypt_cryptojs_aes_stores(data)
    188                 pass
    189         if not success:
--> 190             raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
    191 
    192     decoded_stores = json.loads(plaintext)

Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers
```
I have tried to uninstall it, upgrade it,etc...

I'm using 
python 3.10+
yfinance 0.2.6
MacOS monterrey
<br>
Thanks

**Comment by ValueRaider** [comment]
Duplicate issue

**Comment by onesoned** [comment]
1) cmd --> pip install yfinance --upgrade

2) 
ticker = "aapl"
import yfinance as yf
tickerYF = yf.Ticker(ticker)
print(tickerYF.info)

3) result:
Traceback (most recent call last):
  File "C:\Users\###\source\repos\2021_12_15 Google API Python\2022_03_09 API\tester.py\00 yahooFinance tester.py", line 49, in <module>
    print(tickerYF.info)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\ticker.py", line 142, in info
    return self.get_info()
  File "C:\Program Files\Python37\lib\site-packages\yfinance\base.py", line 1268, in get_info
    data = self._quote.info
  File "C:\Program Files\Python37\lib\site-packages\yfinance\scrapers\quote.py", line 95, in info
    self._scrape(self.proxy)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\scrapers\quote.py", line 124, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 41, in wrapped
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 307, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data, keys)
  File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 162, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response")
Exception: yfinance failed to decrypt Yahoo data response

**Comment by ValueRaider** [comment]
Move to a fresh new Issue.
