### ISSUE TITLE
Cannot get ETN data 

### ISSUE THREAD

**Issue by opherh** [ranaroussi/yfinance#1355]
Hello,
First of all - THANK YOU! love this lib.

Running the latest yFinance 0.2.5 on a MAC Os build.
I've been using the yFinance library easily but recently stumbled into an issue with ETNs specifically.
I don't know if by design but it seems like you cannot get data about ETNs:
I've tried CWEB and GDXU.

Error:
0.2.5
GDXU: Yahoo did not return share count in date range 2021-07-27 00:00:00-04:00 -> 2023-01-27 00:00:00-05:00
Fetch Error
0.2.5
CWEB: Yahoo did not return share count in date range 2021-07-27 00:00:00-04:00 -> 2023-01-27 00:00:00-05:00
Fetch Error

Code:
def get_current_price(symbol):
    try:
        ticker = yf.Ticker(symbol).basic_info
        market_price = ticker['last_price']
        return market_price
    except:
        return "Fetch Error"

**Comment by ValueRaider** [comment]
Those errors cannot possibly be generated by that code.

**Comment by opherh** [comment]
> def get_current_price(symbol):
> try:
> ticker = yf.Ticker(symbol).basic_info
> market_price = ticker['last_price']
> return market_price
> except:
> return "Fetch Error"

It did.
I ran just the two lines:
ticker = yf.Ticker("GDXU").basic_info
print(market_price = ticker['last_price'])

Got in return the same error with the decryption error as well (and i'm on 0.2.5):
0.2.5
GDXU: Yahoo did not return share count in date range 2021-07-28 00:00:00-04:00 -> 2023-01-28 00:00:00-05:00
Traceback (most recent call last):
  File "/Users/opherh/Desktop/TradeJournal/trading-journal/server/csv_parser.py", line 67, in <module>
    print(market_price = ticker['last_price'])
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/base.py", line 92, in __getitem__
    if not k in self.keys():
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/base.py", line 85, in keys
    attrs = utils.attributes(self)
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/utils.py", line 59, in attributes
    return {
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/utils.py", line 61, in <dictcomp>
    if name[0] != '_' and name not in disallowed_names and hasattr(obj, name)}
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/base.py", line 358, in market_cap
    self._mcap = self.shares * self.last_price
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/base.py", line 199, in shares
    shares = self._tkr.get_shares()
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/base.py", line 1437, in get_shares
    data = self._fundamentals.shares
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/scrapers/fundamentals.py", line 40, in shares
    self._scrape_shares(self.proxy)
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/scrapers/fundamentals.py", line 80, in _scrape_shares
    self._scrape_basics(proxy)
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/scrapers/fundamentals.py", line 48, in _scrape_basics
    self._financials_data = self._data.get_json_data_stores('financials', proxy)
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/data.py", line 256, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "/opt/homebrew/lib/python3.10/site-packages/yfinance/data.py", line 190, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

**Comment by opherh** [comment]
Just upgraded to 0.2.9 and it seems to work now!
Changed it to fast_info and now it works :)

Thanks!
