### ISSUE TITLE
Exception when do ticker.info

### ISSUE THREAD

**Issue by robinhftw** [ranaroussi/yfinance#1356]
I'm using Ubuntu 20.04, Python 3.8.10, yfinance-0.2.6

>>> import yfinance as yf
>>> ticker = yf.Ticker("TSLA")
>>> ticker.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/ticker.py", line 142, in info
    return self.get_info()
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/base.py", line 1220, in get_info
    data = self._quote.info
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/scrapers/quote.py", line 96, in info
    self._scrape(self.proxy)
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/scrapers/quote.py", line 125, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/data.py", line 256, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "/home/user/.local/lib/python3.8/site-packages/yfinance/data.py", line 190, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

What am I doing wrong here?

**Comment by ValueRaider** [comment]
Duplicate issue
