### ISSUE TITLE
.info and basic_info methods not working (0.2.9)

### ISSUE THREAD

**Issue by adrianpdvm** [ranaroussi/yfinance#1388]
**yfinance version 0.2.9
python version 3.8.10
windows 11**

- sample code:

_msft = yf.Ticker("MSFT")
msft.info_

- error message_

_Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "D:\folder\pycharm\venv\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "D:\folder\pycharm\venv\lib\site-packages\yfinance\base.py", line 894, in get_info
    data = self._quote.info
  File "D:\folder\pycharm\venv\lib\site-packages\yfinance\scrapers\quote.py", line 27, in info
    self._scrape(self.proxy)
  File "D:\folder\pycharm\venv\lib\site-packages\yfinance\scrapers\quote.py", line 58, in _scrape
    **quote_summary_store = json_data['QuoteSummaryStore']
TypeError: string indices must be integers**_

The basic_info method not working either _('Ticker' object has no attribute 'basic_info')_. Not sure if this is an open issue (didn't find it) or is just bad config on my side. 

Any idea?

Thank you!

**Comment by Bmainente** [comment]
try changing basic_info to fast_info

**Comment by ValueRaider** [comment]
`basic_info` should still work.

> quote_summary_store = json_data['QuoteSummaryStore']
> TypeError: string indices must be integers

This suggests old version. How exactly did you confirm your version?

**Comment by adrianpdvm** [comment]
Ok guys my bad, the problem was that the package within the pycharm project was not updated. I updated to the latest version and it works.

Thank you and apologies
