### ISSUE TITLE
info fails for BRKB

### ISSUE THREAD

**Issue by headdab** [ranaroussi/yfinance#140]
I've tried BRKB and BRK.B with the same results:

>>> yf.Ticker('BRK.B').info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/estes/.local/lib/python3.6/site-packages/yfinance/ticker.py", line 122, in info
    return self.get_info()
  File "/home/estes/.local/lib/python3.6/site-packages/yfinance/base.py", line 360, in get_info
    self._get_fundamentals(proxy)
  File "/home/estes/.local/lib/python3.6/site-packages/yfinance/base.py", line 324, in _get_fundamentals
    key[0]['yearly'] = cleanup(data[item][key[2]])
  File "/home/estes/.local/lib/python3.6/site-packages/yfinance/base.py", line 235, in cleanup
    df = _pd.DataFrame(data).drop(columns=['maxAge'])
  File "/home/estes/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 4117, in drop
    errors=errors,
  File "/home/estes/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/estes/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/estes/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['maxAge'] not found in axis"

**Comment by jsultan2323** [comment]
The correct ticker is 'BRK-B'. If you run into a problem like that then I suggest heading over to finance.yahoo.com to see which ticker value matches the security name.

**Comment by headdab** [comment]
I thought I tried that.  Both brkb and brk.b return results, but the former becomes brk-b as you noted and   brk.b returns something else.  Thanks.
