### ISSUE TITLE
TypeError("unsupported operand type(s) for -: 'str' and 'int'") when downloading price data

### ISSUE THREAD

**Issue by dippudo** [ranaroussi/yfinance#1497]
The ```yf.download``` method does not seem to be working as of late for me, it gives me the error: ```TypeError("unsupported operand type(s) for -: 'str' and 'int'")``` when download stock data with ``period='max'`` or with ``start`` and ``end`` parameters.

---

To prove this was not an error on my end, I followed the example in the documentation:
![image](https://user-images.githubusercontent.com/107745404/232230323-c1de53a3-44ce-4579-a3c2-0cb786f8d870.png)
![image](https://user-images.githubusercontent.com/107745404/232315400-5bb58b48-e1c0-4c9d-b787-fa0ec4874c13.png)

And here was the output (imported yfinance as yf):
```
2 Failed downloads:
- AAPL: TypeError("unsupported operand type(s) for -: 'str' and 'int'")
AAPL: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 833, in pandas._libs.parsers.TextReader.read_low_memory
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\multi.py", line 225, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust, repair,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\multi.py", line 244, in _download_one
    return Ticker(ticker).history(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\base.py", line 154, in history
    tz = self._get_ticker_tz(proxy, timeout)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\base.py", line 930, in _get_ticker_tz
    cache = utils.get_tz_cache()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 967, in get_tz_cache
    _tz_cache = _TzCache()
                ^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 893, in __init__
    self._migrate_cache_tkr_tz()
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 934, in _migrate_cache_tkr_tz
    df = _pd.read_csv(old_cache_file_path, index_col="Ticker")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 240, in read
    index, columns, col_dict = self._get_empty_meta(
                               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\base_parser.py", line 1047, in _get_empty_meta
    columns.pop(n - i)
                ~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'

- SPY: TypeError("unsupported operand type(s) for -: 'str' and 'int'")
SPY: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 833, in pandas._libs.parsers.TextReader.read_low_memory
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\multi.py", line 225, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust, repair,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\multi.py", line 244, in _download_one
    return Ticker(ticker).history(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\base.py", line 154, in history
    tz = self._get_ticker_tz(proxy, timeout)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\base.py", line 930, in _get_ticker_tz
    cache = utils.get_tz_cache()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 967, in get_tz_cache
    _tz_cache = _TzCache()
                ^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 893, in __init__
    self._migrate_cache_tkr_tz()
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 934, in _migrate_cache_tkr_tz
    df = _pd.read_csv(old_cache_file_path, index_col="Ticker")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 240, in read
    index, columns, col_dict = self._get_empty_meta(
                               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\base_parser.py", line 1047, in _get_empty_meta
    columns.pop(n - i)
                ~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Has anyone else been experiencing this issue? Is this a problem on yfinance's end? How can this be resolved?

Thanks

_Originally posted by @dippudo in https://github.com/ranaroussi/yfinance/discussions/1495_

**Comment by dippudo** [comment]
The original discussion: https://github.com/ranaroussi/yfinance/discussions/1495

**Comment by ValueRaider** [comment]
Try branch `hotfix/tz-cache-migrate-error` and report back.

**Comment by dippudo** [comment]
> Try branch `hotfix/tz-cache-migrate-error` and report back.

Thank you, it seems to have worked:

1) using ``start`` and ``end`` parameters:
![image](https://user-images.githubusercontent.com/107745404/232320484-8907f183-3d5c-42da-89c7-ac2882232ece.png)

2) using ``period='max'``
![image](https://user-images.githubusercontent.com/107745404/232320734-b3ce5f9a-d54f-4d6d-a816-b641b733fbfc.png)

I see that you have just added an ``except`` clause for the TypeError which fixed it :)

Could you help me explain how this error came about, and why other people may not be able to recreate the error? And also, should I use this branch in the meantime before ``main`` gets patched?

Thanks again

**Comment by ValueRaider** [comment]
Converting "2017-01-01" to a sensible timestamp requires the symbol timezone. `yfinance` caches this in your system to avoid double web requests so it's user-specific. Obviously depends on the symbols you've requested, but also on `yfinance` version last time cache had R/W - there's been several caching systems since last summer, `yfinance` tries to upgrade it to latest system but the early systems were vulnerable to corruption so upgrade fails.

**Comment by dippudo** [comment]
Oh ok I see, if I use ``pip install yfinance --upgrade --no-cache-dir`` now, as mentioned in the docs, would that upgrade it to the latest system and fix the cache issue for me?

**Comment by ValueRaider** [comment]
Yes
