### ISSUE TITLE
Error when using ticker.info

### ISSUE THREAD

**Issue by chrisaasan** [ranaroussi/yfinance#150]
Here is the code. I think it's reproducible.
```python
>>> import yfinance as yf
>>> ticker = yf.Ticker("SFL")
>>> print(ticker.info["shortName"])

Error:
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(ticker.info["shortName"])
  File "C:\Users\chris\AppData\Local\Programs\Python\Python36\lib\site-packages\yfinance\ticker.py", line 134, in info
    return self.get_info()
  File "C:\Users\chris\AppData\Local\Programs\Python\Python36\lib\site-packages\yfinance\base.py", line 406, in get_info
    self._get_fundamentals(proxy)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python36\lib\site-packages\yfinance\base.py", line 356, in _get_fundamentals
    key[0]['yearly'] = cleanup(data[item][key[2]])
KeyError: 'cashflowStatements'

**Comment by mariusgarbowski** [comment]
I hade the same issue with "MMK.VI". Here is how i made a workaround, so that the error doesn't occur any more when retrieving data for a list of ticker symbols (from line 358):

```        
        for key in (
            (self._cashflow, 'cashflowStatement', 'cashflowStatements'),
            (self._balancesheet, 'balanceSheet', 'balanceSheetStatements'),
            (self._financials, 'incomeStatement', 'incomeStatementHistory')
        ):

            item = key[1] + 'History'
            if isinstance(data.get(item), dict):
                try:
                    key[0]['yearly'] = cleanup(data[item][key[2]])

                except KeyError:
                    key[0]['yearly'] = None

            item = key[1]+'HistoryQuarterly'
            if isinstance(data.get(item), dict):
                try:
                    key[0]['quarterly'] = cleanup(data[item][key[2]])

                except KeyError:
                    key[0]['quarterly'] = None

        # earnings
        if isinstance(data.get('earnings'), dict):
            try:
                earnings = data['earnings']['financialsChart']
                df = _pd.DataFrame(earnings['yearly']).set_index('date')
                df.columns = utils.camel2title(df.columns)
                df.index.name = 'Year'
                self._earnings['yearly'] = df

                df = _pd.DataFrame(earnings['quarterly']).set_index('date')
                df.columns = utils.camel2title(df.columns)
                df.index.name = 'Quarter'
                self._earnings['quarterly'] = df

            except KeyError:
                self._earnings['yearly'] = None
                self._earnings['quarterly'] = None

        self._fundamentals = True
```

Unfortunaly (or fortunately) the data is there, but not in the field, which is selected by this library. If you look in the source code for financials, balance sheet etc. you will find it in json (all the "raw" keys) below the faulty called fields.
@ranaroussi this could be a huge improvement.

**Comment by silvavn** [comment]
Issue is now solved. Code from OP runs.
