### ISSUE TITLE
quarterly_statment returning error "yfinance failed to decrypt yahoo data response"

### ISSUE THREAD

**Issue by bharathkumarchowdary** [ranaroussi/yfinance#1520]
Code for Reproduction:
`yfinance.Ticker("MSFT").quarterly_incomestmt`

Result
 ```
Traceback (most recent call last):
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/findancials.py", line 69, in <module>
    qtly = stock.quarterly_incomestmt  # Recommended and latest use case
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/ticker.py", line 174, in quarterly_incomestmt
    return self.quarterly_income_stmt
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/ticker.py", line 166, in quarterly_income_stmt
    return self.get_income_stmt(pretty=True, freq='quarterly')
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/base.py", line 1375, in get_income_stmt
    data = self._fundamentals.financials.get_income_time_series(freq=freq, proxy=proxy)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/scrapers/fundamentals.py", line 113, in get_income_time_series
    res[freq] = self._fetch_time_series("income", freq, proxy=None)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/scrapers/fundamentals.py", line 142, in _fetch_time_series
    statement = self._create_financials_table(name, timescale, proxy)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/scrapers/fundamentals.py", line 155, in _create_financials_table
    keys = self._get_datastore_keys(name, proxy)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/scrapers/fundamentals.py", line 162, in _get_datastore_keys
    data_stores = self._data.get_json_data_stores(sub_page, proxy)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/data.py", line 41, in wrapped
    return func(*args, **kwargs)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/data.py", line 307, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data, keys)
  File "/Users/bharathkumargundala/otsiot/DwnldStkFromAPI/venv/lib/python3.9/site-packages/yfinance/data.py", line 162, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response")
Exception: yfinance failed to decrypt Yahoo data response

```
- `yfinance` version 0.2.9 and Python version 3.11.1
- macOS Ventura 13.3.1

**Comment by eaglepix** [comment]
yfinance.Ticker("MSFT").info has the same error message.
yfinance version 0.2.9 and Python version 3.8.16
Windows 10
