### ISSUE TITLE
forwardPE stopped to work , seems to be I used it today 

### ISSUE THREAD

**Issue by Sandy4321** [ranaroussi/yfinance#1619]
forwardPE stopped to work , seems to be I used it today 

aapl = yf.Ticker("aapl")
aapl.info['forwardPE']
Traceback (most recent call last):
  Debug Console, prompt 135, line 1
    import os
  File "c:\my_py_environments\py310_torch_cuda_july2023\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "c:\my_py_environments\py310_torch_cuda_july2023\lib\site-packages\yfinance\base.py", line 1501, in get_info
    data = self._quote.info
  File "c:\my_py_environments\py310_torch_cuda_july2023\lib\site-packages\yfinance\scrapers\quote.py", line 563, in info
    self._fetch(self.proxy)
  File "c:\my_py_environments\py310_torch_cuda_july2023\lib\site-packages\yfinance\scrapers\quote.py", line 592, in _fetch
    result = self._data.get_raw_json(
  File "c:\my_py_environments\py310_torch_cuda_july2023\lib\site-packages\yfinance\data.py", line 75, in get_raw_json
    response.raise_for_status()
  File "c:\my_py_environments\py310_torch_cuda_july2023\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

also not working 
tsla = yf.Ticker("TSLA")
tsla.info
print(f"Market Cap : {tsla.info['marketCap']}\n")
print(f"Employees : {tsla.info['fullTimeEmployees']}\n")
print(f"Business Summary : \n{tsla.info['longBusinessSummary']}")

**Comment by ValueRaider** [comment]
Stop spamming and read the issue instructions more carefully. yfinance is fine

**Comment by Sandy4321** [comment]
sorry , how to find this 'New issue' instructions
