### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ohenley** [ranaroussi/yfinance#162]
Fetch the 'DVY' ticker and you get this: 

``` python
>>> yf.Ticker('DVY').info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 304, in _get_fundamentals
    s[s.index == 'ratingYear']['Value'].values[0],
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by ohenley** [comment]
And then if you fix this, you will run into this other one:
```
>>> yf.Ticker('DVY').info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 423, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 321, in _get_fundamentals
    if 'regularMarketPrice' in self._info['regularMarketPrice']:
KeyError: 'regularMarketPrice'
```

**Comment by ohenley** [comment]
Ok, looks like the raw data is not good to start with. Once the two previous errors are 'fixed', you get this:
```
>>> yf.Ticker('DVY').info
{'exchange': 'NGM', 'shortName': 'iShares Select Dividend ETF', 'longName': 'iShares Trust - iShares Select Dividend ETF', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EST', 'isEsgPopulated': False, 'gmtOffSetMilliseconds': '-18000000', 'quoteType': 'ETF', 'symbol': 'DVY', 'messageBoardId': 'finmb_22699479', 'market': 'us_market', 'err': {'elapsedTime': 10, 'status': 404, 'statusCode': 404, 'statusText': 'Not Found', 'requestUri': 'http://iquery.finance.yahoo.com:4080/v10/finance/quoteSummary/DVY?formatted=true&crumb=PCxKRl7b7eB&lang=en-US&region=US&modules=defaultKeyStatistics%2CassetProfile%2CtopHoldings%2CfundPerformance%2CfundProfile%2CesgScores&ssl=true', 'headers': {'referrer-policy': 'no-referrer-when-downgrade', 'x-xss-protection': '1; mode=block', 'server': 'ATS', 'x-frame-options': 'SAMEORIGIN', 'x-envoy-decorator-operation': 'finance-quote-summary-api--production-gq1.finance-k8s.svc.yahoo.local:4080/*', 'x-envoy-upstream-service-time': '3', 'via': 'http/1.1 media-router-omega117.prod.media.gq1.yahoo.com (ApacheTrafficServer [cMsSfW]), http/1.1 media-ncache-api7005.prod.media.gq1.yahoo.com (ApacheTrafficServer [cMsSfW]), http/1.1 media-router-api73.prod.media.gq1.yahoo.com (ApacheTrafficServer [cMsSf ])', 'content-type': 'application/json', 'x-request-id': '79317d81-1c7d-90d8-ad82-c21aa278a044', 'date': 'Tue, 07 Jan 2020 15:59:32 GMT', 'cache-control': 'max-age=0, private', 'vary': 'Origin', 'x-content-type-options': 'nosniff', 'expires': '-1', 'y-rid': '5oovrllf19an4', 'content-length': '216', 'connection': 'keep-alive', 'age': '0'}, 'responseText': '{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for any of the summaryTypes=defaultKeyStatistics,assetProfile,topHoldings,fundPerformance,fundProfile,esgScores"}}}', 'responseXML': None}, 'regularMarketPrice': '', 'logo_url': ''}
```

**Comment by silvavn** [comment]
I executed the two commands you provided as example
```python
>>> yf.Ticker('DVY').info
{'previousClose': 122.1,
 'regularMarketOpen': 122.48,
 'twoHundredDayAverage': 107.76007,
 'trailingAnnualDividendYield': 0.030106472,
 'payoutRatio': None,
 'volume24Hr': None,
 'regularMarketDayHigh': 122.49,
 'navPrice': 118.97,
 'averageDailyVolume10Day': 582714,
 'totalAssets': 18495580160,
 'regularMarketPreviousClose': 122.1,
 'fiftyDayAverage': 120.07543,
 'trailingAnnualDividendRate': 3.676,
 'open': 122.48,
 'toCurrency': None,
 'averageVolume10days': 582714,
 'expireDate': None,
 'yield': 0.0299,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 121.7501,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 407496,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': None,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 789339,
 'priceToSalesTrailing12Months': None,
 'dayLow': 121.7501,
 'ask': 122.32,
 'ytdReturn': None,
 'askSize': 800,
 'volume': 407496,
 'fiftyTwoWeekHigh': 124.34,
 'forwardPE': None,
 'maxAge': 1,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 76.83,
 'bid': 121.22,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 900,
 'dayHigh': 122.49,
 'exchange': 'NGM',
 'shortName': 'iShares Select Dividend ETF',
 'longName': 'iShares Select Dividend ETF',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'ETF',
 'symbol': 'DVY',
 'messageBoardId': 'finmb_22699479',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': None,
 'beta3Year': 1,
 'profitMargins': None,
 'enterpriseToEbitda': None,
 '52WeekChange': None,
 'morningStarRiskRating': None,
 'forwardEps': None,
 'revenueQuarterlyGrowth': None,
 'fundInceptionDate': 1067817600,
 'annualReportExpenseRatio': None,
 'bookValue': None,
 'fundFamily': 'iShares',
 'lastFiscalYearEnd': None,
 'netIncomeToCommon': None,
 'trailingEps': None,
 'lastDividendValue': None,
 'SandP52WeekChange': None,
 'priceToBook': None,
 'nextFiscalYearEnd': None,
 'mostRecentQuarter': None,
 'enterpriseValue': None,
 'threeYearAverageReturn': 0.1176,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': 'Exchange Traded Fund',
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': None,
 'pegRatio': None,
 'lastCapGain': None,
 'category': None,
 'fiveYearAverageReturn': 0.120799996,
 'phone': '800-474-2737',
 'longBusinessSummary': 'The investment seeks to track the investment results of the Dow Jones U.S. Select Dividend Index composed of relatively high dividend paying U.S. equities.\n The fund generally invests at least 90% of its assets in securities of the underlying index and in depositary receipts representing securities of the underlying index. The underlying index measures the performance of the U.S.&#39;s leading stocks by dividend yield.',
 'companyOfficers': [],
 'regularMarketPrice': 122.3,
 'logo_url': ''}
```
and

```python
>>> yf.Ticker('INRG.L').info
{'zip': '19462',
 'sector': 'Healthcare',
 'fullTimeEmployees': 1720,
 'longBusinessSummary': "Accolade, Inc. develops and provides technology-enabled solutions that help people to understand, navigate, and utilize the healthcare system and their workplace benefits in the United States. The company offers a platform with cloud-based technology and multimodal support from a team of health assistants and clinicians, including nurses, physician medical directors, and behavioral health specialists. It also provides second opinion consultation and health care decision support services. The company serves employers who provide their employees and their employees' families a single place to turn for their health, healthcare, and benefits needs. Accolade, Inc. was founded in 2007 and is headquartered in Plymouth Meeting, Pennsylvania.",
 'city': 'Plymouth Meeting',
 'phone': '206 926 8100',
 'state': 'PA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.accolade.com',
 'maxAge': 1,
 'address1': '660 West Germantown Pike',
 'industry': 'Health Information Services',
 'address2': 'Suite 500',
 'previousClose': 50.08,
 'regularMarketOpen': 50.77,
 'twoHundredDayAverage': 48.226204,
 'trailingAnnualDividendYield': None,
 'payoutRatio': 0,
 'volume24Hr': None,
 'regularMarketDayHigh': 52.15,
 'navPrice': None,
 'averageDailyVolume10Day': 585585,
 'totalAssets': None,
 'regularMarketPreviousClose': 50.08,
 'fiftyDayAverage': 46.386856,
 'trailingAnnualDividendRate': None,
 'open': 50.77,
 'toCurrency': None,
 'averageVolume10days': 585585,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 49.75,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 341616,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 2993384192,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 876395,
 'priceToSalesTrailing12Months': 17.57114,
 'dayLow': 49.75,
 'ask': 51.39,
 'ytdReturn': None,
 'askSize': 1200,
 'volume': 341616,
 'fiftyTwoWeekHigh': 65.25,
 'forwardPE': None,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 0.55,
 'bid': 51.26,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 800,
 'dayHigh': 52.15,
 'exchange': 'NMS',
 'shortName': 'Accolade, Inc.',
 'longName': 'Accolade, Inc.',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'ACCD',
 'messageBoardId': 'finmb_84942090',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 15.193,
 'beta3Year': None,
 'profitMargins': -0.29733,
 'enterpriseToEbitda': -60.017,
 '52WeekChange': 91.76363,
 'morningStarRiskRating': None,
 'forwardEps': None,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 58670800,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': None,
 'sharesShort': 3735089,
 'sharesPercentSharesOut': 0.0637,
 'fundFamily': None,
 'lastFiscalYearEnd': 1614470400,
 'heldPercentInstitutions': 0.72227997,
 'netIncomeToCommon': -50652000,
 'trailingEps': None,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.30859518,
 'priceToBook': None,
 'heldPercentInsiders': 0.0652,
 'nextFiscalYearEnd': 1677542400,
 'mostRecentQuarter': 1614470400,
 'shortRatio': 4.54,
 'sharesShortPreviousMonthDate': 1618444800,
 'floatShares': 50278506,
 'enterpriseValue': 2588247552,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': None,
 'dateShortInterest': 1620950400,
 'pegRatio': -1.87,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0979,
 'sharesShortPriorMonth': 3331419,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 51.02,
 'logo_url': 'https://logo.clearbit.com/accolade.com'}
```

Is this the output you expected?
