### ISSUE TITLE
KeyError: "['maxAge'] not found in axis"

### ISSUE THREAD

**Issue by ohenley** [ranaroussi/yfinance#163]
Try the following:
```
>>> import yfinance as yf
>>> yf.Ticker('BNKO').info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 423, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 373, in _get_fundamentals
    key[0]['yearly'] = cleanup(data[item][key[2]])
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 252, in cleanup
    df = _pd.DataFrame(data).drop(columns=['maxAge'])
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 4117, in drop
    errors=errors,
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['maxAge'] not found in axis"
```

**Comment by Puhtooie** [comment]
got the same error using `.get_balance_sheet()` as well as a few other function calls, and `.fundementals `

Seems to be a consistent error across multiple symbols

**Comment by Puhtooie** [comment]
I put in the request for the change. I think the below code should fix it.

  ```
def cleanup(data):
           
            #df = _pd.DataFrame(data).drop(columns=['maxAge'])
            #altered line ^
            df = _pd.DataFrame(data)

            if 'maxAge' in df.columns:
                df = df.drop(columns=['maxAge'])
```

**Comment by dog5tar** [comment]
@Puhtooie can you link up the PR. I have this issue and would like to path my local but can't find your PR.
