### ISSUE TITLE
Attributes in yf.Ticker("MSFT") as dict

### ISSUE THREAD

**Issue by Puhtooie** [ranaroussi/yfinance#167]
Is there a good reason the attributes in `Class Ticker(TickerBase)` aren't stored in a dict instead of `self._recommendations` etc? 

It calls and stores all of the data just fine when I just do 
`for i in symbols:
    tickers[i] = yf.Ticker(i)
`
but when I call the funcs for the respective attribute value I eventually get: 

`Traceback (most recent call last):
  File "C:\Users\misc\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a66a7cb329a7>", line 28, in <module>
    f = Fundamentals()
  File "<ipython-input-2-a66a7cb329a7>", line 16, in __init__
    self.tickers[i]['balance_sheet'] = self.tickers[i]['all'].get_balance_sheet()
  File "C:\Users\misc\venv\lib\site-packages\yfinance\base.py", line 441, in get_balance_sheet
    return self.get_balancesheet(proxy, as_dict, freq)
  File "C:\Users\misc\venv\lib\site-packages\yfinance\base.py", line 434, in get_balancesheet
    self._get_fundamentals(proxy)
  File "C:\Users\misc\venv\lib\site-packages\yfinance\base.py", line 356, in _get_fundamentals
    key[0]['yearly'] = cleanup(data[item][key[2]])
  File "C:\Users\misc\venv\lib\site-packages\yfinance\base.py", line 246, in cleanup
    df = _pd.DataFrame(data).drop(columns=['maxAge'])
  File "C:\Users\misc\venv\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\misc\venv\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\misc\venv\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Brent\PycharmProjects\binane\venv\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['maxAge'] not found in axis"`

So, is there something that I'm missing that makes it so that it's necessary to store each value as an attribute instead of in a nested dictionary? Because, if they were all stored in a dictionary that should make loading and iterating through the data much more simple, and it seems like it might also decrease the amount of function calls necessary to load and iterate the data.

I figured I'd ask here before starting to attempt refactoring the code. I'm mediocre at best and wouldn't want to waste a couple hours just to find out I missed a crucial part of the code.

**Comment by silvavn** [comment]
Question is unclear, and needs and clear example code.
