### ISSUE TITLE
Running `.institutional_holders` give the following error - ValueError: time data "..." doesn't match format "%B %d, %Y", at position 1

### ISSUE THREAD

**Issue by Valachio** [ranaroussi/yfinance#1685]
### Describe bug

I was scraping the ticker ACST and getting institutional holders when I ran into this issue.

The issue can be replicated like this:

```
import yfinance
stock = yfinance.Ticker('ACST')
stock.institutional_holders # Gives error
```

The full error is:

```
ValueError: time data "Jun 29, 2023" doesn't match format "%B %d, %Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

I'm using Python 3.11, and yfinance v0.2.28

### Simple code that reproduces your problem

import yfinance
stock = yfinance.Ticker('ACST')
stock.institutional_holders # Gives error

### Debug log

/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/yfinance/scrapers/holders.py:39: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  holders = pd.read_html(resp.text)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/yfinance/ticker.py", line 114, in institutional_holders
    return self.get_institutional_holders()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/yfinance/base.py", line 1662, in get_institutional_holders
    data = self._holders.institutional
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/yfinance/scrapers/holders.py", line 26, in institutional
    self._scrape(self.proxy)
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/yfinance/scrapers/holders.py", line 63, in _scrape
    self._mutualfund['Date Reported'] = pd.to_datetime(
                                        ^^^^^^^^^^^^^^^
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 488, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jack/Projects/ais/aisenv/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 519, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 534, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 355, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "Jun 29, 2023" doesn't match format "%B %d, %Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

### `yfinance` version

0.2.28

### Python version

3.11

### Operating system

M2 Macbook Air; Ventura 13.1

**Comment by rickturner2001** [comment]
I am unable to reproduct this on my machine. Are you still facing issues with this?

**Comment by NathanaelV** [comment]
I had the same error:

```
FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
```

**Comment by speedbits** [comment]
I am getting the same error. I am using python 3.9 version on windows 10.
