### ISSUE TITLE
KeyError in yfinance when making concurrent requests

### ISSUE THREAD

**Issue by AbhishekSRaut** [ranaroussi/yfinance#1696]
When attempting to download financial data using the yfinance library in Python and making concurrent requests with the help of threading, a KeyError is raised. This error occurs when attempting to download data for certain stock tickers, such as 'NIFTY_FIN_SERVICE.NS', and is not consistent for all provided tickers.
It means, This key error come to random companies.
Code:

```
import yfinance as yf
import pandas as pd
import threading
import os

def downloader(company):
    filename = os.path.join(f'{company}', f'{company}.csv')
    check1 = os.path.exists(filename)
    if check1:
        os.remove(filename)
    data = yf.download(tickers=f'{company}', period='60d', interval='5m', group_by='ticker', auto_adjust=False)
    df = pd.DataFrame(data)
    df.reset_index(drop=False, inplace=True)
    df.rename(columns={'Datetime': 'datetime'}, inplace=True)
    df.to_csv(filename, index=False, columns=['datetime', 'Open', 'High', 'Low', 'Close', 'Volume'])

data_list = ['^NSEI', '^NSEBANK', 'NIFTY_FIN_SERVICE.NS']
threads = []
for i in data_list:
    thread = threading.Thread(target=downloader, args=(i,), daemon=True)
    threads.append(thread)
    thread.start()
print('All threads have started!')
for thread in threads:
    thread.join()

```

complete error:
Traceback (most recent call last):
  File "E:\share market\yahu Finance\instent running\automated_analysis\5_EMA\main.py", line 52, in downloader
    data = yf.download(tickers=f'{company}', period='60d', interval='5m', group_by='ticker', auto_adjust=False)
  File "C:\Users\abhishek\AppData\Roaming\Python\Python311\site-packages\yfinance\utils.py", line 114, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\abhishek\AppData\Roaming\Python\Python311\site-packages\yfinance\multi.py", line 212, in download
    return shared._DFS[ticker]
KeyError: 'NIFTY_FIN_SERVICE.NS'

**Comment by AbhishekSRaut** [comment]
Solved.
We have to use session from requests.
you can use following code:

```
import yfinance as yf
import pandas as pd
import threading
import requests
from requests import Session
import os

yfinance_session = Session()

def downloader(company):
    filename = os.path.join(f'{company}', f'{company}.csv')
    check1 = os.path.exists(filename)
    if check1:
        os.remove(filename)
    data = yf.download(tickers=f'{company}', period='60d', interval='5m', group_by='ticker', auto_adjust=False,session=yfinance_session)
    df = pd.DataFrame(data)
    df.reset_index(drop=False, inplace=True)
    df.rename(columns={'Datetime': 'datetime'}, inplace=True)
    df.to_csv(filename, index=False, columns=['datetime', 'Open', 'High', 'Low', 'Close', 'Volume'])

data_list = ['^NSEI', '^NSEBANK', 'NIFTY_FIN_SERVICE.NS']
threads = []
for i in data_list:
    thread = threading.Thread(target=downloader, args=(i,), daemon=True)
    threads.append(thread)
    thread.start()
print('All threads have started!')
for thread in threads:
    thread.join()

```

**Comment by andrewyur** [comment]
This is still an issue when using yf while handling concurrent requests with flask, even when the session is used:

```
from flask import Flask
import yfinance as yf
from requests import Session

app = Flask(__name__)

yf_session = Session()

@app.route("/")
def hello_world():
   for ticker in ["APO", "AMGN", "C", "^GSPC"]:
      yf.download(ticker, period="5y", interval="1d", session=yf_session)
   return "working"
```

when this route is hit with 2 requests at once, the following error is produced:

```
Traceback (most recent call last):
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/app.py", line 12, in hello_world
    yf.download(ticker, period="5y", interval="1d", session=yf_session)
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/school/Classes/ssmif/flask-test/.venv/lib/python3.12/site-packages/yfinance/multi.py", line 205, in download
    return shared._DFS[ticker]
           ^^^^^^^^^^^^^^^^^^^
KeyError: 'APO'
```


Is this a problem with the way i am using yfinance or with my flask configuration?

**Comment by ValueRaider** [comment]
Don't pile multithreading on top of multithreading, it will break `shared._DFS`. `download` is already multithreaded and carefully manages `shared._DFS`
