### ISSUE TITLE
Issue dling OHLC data using start/end params within either the history or download methods

### ISSUE THREAD

**Issue by cppt** [ranaroussi/yfinance#1714]
I found a blog post demoing the use of start and end params for pulling OHLC info into Python via the api (so I presume this should have worked at some point).  

Call is as follows:
`data = yf.download("AMZN AAPL GOOG", start="2017-01-01", end="2017-04-30")`

Which returns the following error:
```
data = yf.download("AMZN AAPL GOOG", start="2017-01-01", end="2017-04-30")
[*********************100%%**********************]  3 of 3 completed
3 Failed downloads:
['GOOG', 'AMZN', 'AAPL']: TypeError('super(type, obj): obj must be an instance or subtype of type')
```

I get a similar error when using the `history` method to access the data as follows:
`spy.history(start='2023-08-14', end='2023-09-30')`

```
spy.history(start='2023-08-14', end='2023-09-30')
Traceback (most recent call last):

  File "/tmp/ipykernel_375538/1222174949.py", line 1, in <module>
    spy.history(start='2023-08-14', end='2023-09-30')

  File "/home/chris/anaconda3/lib/python3.9/site-packages/yfinance/utils.py", line 114, in wrapper
    result = func(*args, **kwargs)

  File "/home/chris/anaconda3/lib/python3.9/site-packages/yfinance/base.py", line 200, in history
    dt_now = pd.Timestamp.utcnow()

  File "pandas/_libs/tslibs/timestamps.pyx", line 1155, in pandas._libs.tslibs.timestamps.Timestamp.utcnow

  File "pandas/_libs/tslibs/timestamps.pyx", line 1115, in pandas._libs.tslibs.timestamps.Timestamp.now

  File "/home/chris/anaconda3/lib/python3.9/site-packages/pytz/__init__.py", line 228, in fromutc
    return super(utc.__class__, self).fromutc(dt)

TypeError: super(type, obj): obj must be an instance or subtype of type
```

I am able to download OHLC data using the `period` parameter though, as below, but I need data for/between specific dates.  
`spy.history(period='6mo')`

Any guidance would be much appreciated.

**Comment by rickturner2001** [comment]
I am unable to reproduce this error on my machine. Can you give us more insights regarding your hardware, software and maybe even the context in which you are trying to run this code?

**Comment by ValueRaider** [comment]
No more information needed. Look at stack trace - problem is `pandas` and/or `pytz`.
