### ISSUE TITLE
Failed to download symbol EWBC with Python 3.8.10

### ISSUE THREAD

**Issue by dackon** [ranaroussi/yfinance#1731]
### Describe bug

When downloading the symbol 'EWBC,' I encountered an exception with Python 3.8.10, but Python 3.12.0 is working fine.

### Simple code that reproduces your problem

```python
import yfinance as yf
import traceback

def main():
    try:
        tk = yf.Ticker("EWBC")
        df = tk.history(period="3y", repair=True)
    except Exception as e:
        print(e)
        traceback.print_exc()


if __name__ == "__main__":
    main()
```

### Debug log

After running the script, I got this exception:
```log
unsupported operand type(s) for |: 'dict' and 'dict'
Traceback (most recent call last):
  File "src/playground.py", line 9, in main
    df = tk.history(period="3y", repair=True)
  File "/data/projects/py/trade-data-server/.venv/lib/python3.8/site-packages/yfinance/utils.py", line 114, in wrapper
    result = func(*args, **kwargs)
  File "/data/projects/py/trade-data-server/.venv/lib/python3.8/site-packages/yfinance/base.py", line 373, in history
    df = utils.safe_merge_dfs(df, dividends, interval)
  File "/data/projects/py/trade-data-server/.venv/lib/python3.8/site-packages/yfinance/utils.py", line 704, in safe_merge_dfs
    empty_row_data = {c:[_np.nan] for c in const.price_colnames}|{'Volume':[0]}
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

### `yfinance` version

0.2.31

### Python version

3.8.10

### Operating system

ubuntu

**Comment by ValueRaider** [comment]
Dict operand | must be a new feature. Basically merges the 2 dicts, can be replaced with equivalent code. If using old Python is important then submit a patch.

**Comment by dackon** [comment]
Thank you for the reply. I have updated Python.
