### ISSUE TITLE
.get_news() seems to work intermittently; why?

### ISSUE THREAD

**Issue by eltirobert** [ranaroussi/yfinance#1735]
### Describe bug

When I run

msft = yf.Ticker('MSFT')
msft.get_news()

or any other symbol, not necessarily 'MSFT', sometimes it works, but the majority of the time I get: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Why is this? How can I fix it and make it work consistently. It throws my whole script off when even one symbol fails. The same thing happens when calling msft.news

Thanks.

### Simple code that reproduces your problem

msft = yf.Ticker('MSFT')
msft.get_news()

### Debug log

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### `yfinance` version

0.2.31

### Python version

latest

### Operating system

macOS

**Comment by eltirobert** [comment]
Sometimes I have had success passing a proxy to .get_news(proxy = ), but now even that method is not working as it is not accepting any of my proxies. Can someone suggest what can be done? Or maybe in a future version proxies can be fixed, possibly by not using the requests module but rather urllib.

**Comment by Lamassucoding** [comment]
I'm having same exact issue, any update? any work around?
it is intermittent.

**Comment by ValueRaider** [comment]
Does this happen with version >= 0.2.32?

**Comment by Lamassucoding** [comment]
I think so, I used to use old version, it stopped working few months back.
I just upgraded to the new version and still not working.
BTW it is intermitting.
thx

**Comment by Lamassucoding** [comment]
I think I know the issue.
when it start failing, I can see from my packet capture (on wireshark) requests are not leaving my PC.
But if i run the same code from another python interpreter (another window or Visual studio), start working and i see packets on my packet capture.
i think when it hit bad request it get cashed somewhere so when you do same request for same ticker nothing will leave my pc not even one packet.
i hope that can point you in the right direction.
thx

**Comment by Lamassucoding** [comment]
not sure if someone looking into this or not.
today it  (get_news() ) is constantly  failing

**Comment by melgazar9** [comment]
Hey @ValueRaider any idea what's going on with this?

```
>>> import yfinance as yf
>>> t = yf.Ticker('AAPL')

>>> t.news
Traceback (most recent call last):
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yfinance/ticker.py", line 264, in news
    return self.get_news()
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yfinance/base.py", line 512, in get_news
    data = data.json()
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



>>> t.get_news()
Traceback (most recent call last):
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yfinance/base.py", line 512, in get_news
    data = data.json()
  File "/Users/melgazar9/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
