### ISSUE TITLE
Error downloading data for "AAPL": No price data found (1d 2019-01-01 -> 2021-06-12)

### ISSUE THREAD

**Issue by YeakubSadlil** [ranaroussi/yfinance#1797]
### Describe bug

I'm encountering an error when attempting to download AAPL data and stock ticker using yfinance. The specific error message is:
```
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['AAPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2021-01-01)')
```

I tried running the code snippet on other laptops and on Kaggle, where it worked well. However, it fails to download data only on my laptop.

_Troubleshooting Steps Attempted:_

- Reinstalling yfinance
- Checking several date range
- Checking several times on different days
- Checking with different stock tickers

### Simple code that reproduces your problem

```
import pandas as pd
import yfinance as yf

aapl_df = yf.download('AAPL', 
                    start='2019-01-01', 
                    end='2021-06-12',
)
```

### Debug log

```
DEBUG    Entering download()
DEBUG:yfinance:Entering download()
DEBUG     Disabling multithreading because DEBUG logging enabled
DEBUG:yfinance: Disabling multithreading because DEBUG logging enabled
DEBUG     Entering history()
DEBUG:yfinance: Entering history()
DEBUG      AAPL: Yahoo GET parameters: {'period1': '2019-01-01 00:00:00-05:00', 'period2': '2021-01-01 00:00:00-05:00', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
DEBUG:yfinance:  AAPL: Yahoo GET parameters: {'period1': '2019-01-01 00:00:00-05:00', 'period2': '2021-01-01 00:00:00-05:00', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
DEBUG      Entering get()
DEBUG:yfinance:  Entering get()
DEBUG       url=https://query2.finance.yahoo.com/v8/finance/chart/AAPL
DEBUG:yfinance:   url=https://query2.finance.yahoo.com/v8/finance/chart/AAPL
DEBUG       params=frozendict.frozendict({'period1': 1546318800, 'period2': 1609477200, 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'})
DEBUG:yfinance:   params=frozendict.frozendict({'period1': 1546318800, 'period2': 1609477200, 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'})
DEBUG       Entering _get_cookie_and_crumb()
DEBUG:yfinance:   Entering _get_cookie_and_crumb()
DEBUG        cookie_mode = 'basic'
DEBUG:yfinance:    cookie_mode = 'basic'
DEBUG        Entering _get_cookie_and_crumb_basic()
DEBUG:yfinance:    Entering _get_cookie_and_crumb_basic()
ERROR     
          1 Failed download:
ERROR:yfinance: 
 1 Failed download:
ERROR     ['AAPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2021-01-01)')
ERROR:yfinance: ['AAPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2021-01-01)')
DEBUG     ['AAPL']: Traceback (most recent call last):
            File "/home/yakub/.local/lib/python3.10/site-packages/yfinance/multi.py", line 279, in _download_one
            File "/home/yakub/.local/lib/python3.10/site-packages/yfinance/utils.py", line 108, in wrapper
            File "/home/yakub/.local/lib/python3.10/site-packages/yfinance/base.py", line 267, in history
          Exception: %ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2021-01-01)
          
DEBUG:yfinance: ['AAPL']: Traceback (most recent call last):
   File "/home/yakub/.local/lib/python3.10/site-packages/yfinance/multi.py", line 279, in _download_one
   File "/home/yakub/.local/lib/python3.10/site-packages/yfinance/utils.py", line 108, in wrapper
   File "/home/yakub/.local/lib/python3.10/site-packages/yfinance/base.py", line 267, in history
 Exception: %ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2021-01-01)
 
DEBUG    Exiting download()
DEBUG:yfinance:Exiting download()
```

### `yfinance` version

0.2.33

### Python version

3.10.13

### Operating system

Ubuntu 22.04.3 LTS

**Comment by TheLazyGamer** [comment]
I'm experiencing the same issue with Windows 10 and Python version 3.10.2. Happy to provide any log info if needed

**Comment by nzooherd** [comment]
I also can't find AAPL price data when i download through http proxy because I live in China. 
But when I run the code on a cloud vps is USA. Everythin is OK.

**Comment by mckelvin** [comment]
Try to run with `raise_errors=True`, e.g.:

> aapl_df = yf.download('AAPL', 
                    start='2019-01-01', 
                    end='2021-06-12',
                    raise_errors=True
)

Then you will see the underlying errors.

**Comment by jarmo-seljamaa** [comment]
> Try to run with `raise_errors=True`, e.g.:

I believe `raise_errors` is not supported in `.download()`?
