### ISSUE TITLE
peewee.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by harminsoftware** [ranaroussi/yfinance#1821]
### Describe bug

Hi, 
First of all awesome work! this library is a blessing! 
I am using this library in my flask app and when deploying to digital occean app platform, getting below error : 

```
[flask-sample-app] [2024-01-10 21:56:51]   File "/workspace/.heroku/python/lib/python3.12/site-packages/peewee.py", line 3565, in _set_pragmas
[flask-sample-app] [2024-01-10 21:56:51]     cursor.execute('PRAGMA %s = %s;' % (pragma, value))
[flask-sample-app] [2024-01-10 21:56:51] sqlite3.OperationalError: disk I/O error
```

Few notes : 
1. this error does not come while running same app locally. 
2. There is no bulk request to the server, it fails on first request itself. 
3. there is no db in the flask app. this api simply fetch the news for a ticker. 
4. I have tried many help topics online but none of them are helpful. 
5. I saw that some kind of cache is being used by library and suspect if it is affecting this. tried changing location but not helpful. (or don't know what it should be) 

### Simple code that reproduces your problem

import yfinance as yf
stock = yf.Ticker('aapl')
print(stock.news)

### Debug log

```
[flask-sample-app] [2024-01-10 21:56:51] [2024-01-10 21:56:51,479] ERROR in app: Exception on /aapl/news [GET]
[flask-sample-app] [2024-01-10 21:56:51] Traceback (most recent call last):
[flask-sample-app] [2024-01-10 21:56:51]   File "/workspace/.heroku/python/lib/python3.10/site-packages/peewee.py", line 3193, in connect
[flask-sample-app] [2024-01-10 21:56:51]     self._state.set_connection(self._connect())
[flask-sample-app] [2024-01-10 21:56:51]   File "/workspace/.heroku/python/lib/python3.10/site-packages/peewee.py", line 3540, in _connect
[flask-sample-app] [2024-01-10 21:56:51]     self._add_conn_hooks(conn)
[flask-sample-app] [2024-01-10 21:56:51]   File "/workspace/.heroku/python/lib/python3.10/site-packages/peewee.py", line 3550, in _add_conn_hooks
[flask-sample-app] [2024-01-10 21:56:51]     self._set_pragmas(conn)
[flask-sample-app] [2024-01-10 21:56:51]   File "/workspace/.heroku/python/lib/python3.10/site-packages/peewee.py", line 3565, in _set_pragmas
[flask-sample-app] [2024-01-10 21:56:51]     cursor.execute('PRAGMA %s = %s;' % (pragma, value))
[flask-sample-app] [2024-01-10 21:56:51] sqlite3.OperationalError: disk I/O error
```

### `yfinance` version

0.2.33

### Python version

python-3.12.1

### Operating system

Ubuntu-22

**Comment by ValueRaider** [comment]
yfinance has a cache (README Ctrl+F).

Has caused problems on VPSs etc before because path location isn't writable, I thought was solved by allowing cache to fail. If you find a place to store cache, that's better.

**Comment by harminsoftware** [comment]
> yfinance has a cache (README Ctrl+F).
> 
> Has caused problems on VPSs etc before because path location isn't writable, I thought was solved by allowing cache to fail. If you find a place to store cache, that's better.

Thanks @ValueRaider but i already tried setting the cache location to a different place and set up appropriate permission to that, still issue is prevalent.

`from flask import render_template
from app.main import bp
import os
from pandas_datareader import data as pdr
import yfinance as yf

# Set the path for the cache folder
cache_folder = 'temp_cache'

# Create the cache folder if it doesn't exist
if not os.path.exists(cache_folder):
    os.makedirs(cache_folder)

# Set the permissions to 777 for the cache folder
os.chmod(cache_folder, 0o777)

# Set the tz cache location
yf.set_tz_cache_location(cache_folder)


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/<ticker>/news', methods=['GET'])
def news_route(ticker):
    stock = yf.Ticker(ticker)
    return stock.news
`

**Comment by ValueRaider** [comment]
Can you get a better log trace that shows where in yfinance the exception originates?

**Comment by pythoninoffice** [comment]
> Can you get a better log trace that shows where in yfinance the exception originates?

Hi @ValueRaider , not OP but I'm having the same error. My app is running on DigitalOcean's App platform.

I tried to include "chmod -R 777 ." as a build command but that did not seem to work. Attached below full error log.
Appreciate your feedback!



[optjournal] [2024-01-31 19:18:46] Traceback (most recent call last):
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3252, in execute_sql
[optjournal] [2024-01-31 19:18:46]     cursor.execute(sql, params or ())
[optjournal] [2024-01-31 19:18:46] sqlite3.OperationalError: disk I/O error
[optjournal] [2024-01-31 19:18:46] 
[optjournal] [2024-01-31 19:18:46] During handling of the above exception, another exception occurred:
[optjournal] [2024-01-31 19:18:46] 
[optjournal] [2024-01-31 19:18:46] Traceback (most recent call last):
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
[optjournal] [2024-01-31 19:18:46]     response = self.full_dispatch_request()
[optjournal] [2024-01-31 19:18:46]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
[optjournal] [2024-01-31 19:18:46]     rv = self.handle_user_exception(e)
[optjournal] [2024-01-31 19:18:46]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
[optjournal] [2024-01-31 19:18:46]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[optjournal] [2024-01-31 19:18:46]                                                 ^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
[optjournal] [2024-01-31 19:18:46]     rv = self.dispatch_request()
[optjournal] [2024-01-31 19:18:46]          ^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
[optjournal] [2024-01-31 19:18:46]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[optjournal] [2024-01-31 19:18:46]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/api/option_profit_calculator.py", line 124, in get_exp_date_yfinance
[optjournal] [2024-01-31 19:18:46]     bid_price = stock.info['bid']
[optjournal] [2024-01-31 19:18:46]                 ^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/ticker.py", line 154, in info
[optjournal] [2024-01-31 19:18:46]     return self.get_info()
[optjournal] [2024-01-31 19:18:46]            ^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/base.py", line 1784, in get_info
[optjournal] [2024-01-31 19:18:46]     data = self._quote.info
[optjournal] [2024-01-31 19:18:46]            ^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/scrapers/quote.py", line 574, in info
[optjournal] [2024-01-31 19:18:46]     self._fetch_info(self.proxy)
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/scrapers/quote.py", line 649, in _fetch_info
[optjournal] [2024-01-31 19:18:46]     result = self._fetch(proxy, modules=modules)
[optjournal] [2024-01-31 19:18:46]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/scrapers/quote.py", line 638, in _fetch
[optjournal] [2024-01-31 19:18:46]     result = self._data.get_raw_json(_QUOTE_SUMMARY_URL_ + f"/{self._symbol}", user_agent_headers=self._data.user_agent_headers, params=params_dict, proxy=proxy)
[optjournal] [2024-01-31 19:18:46]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/data.py", line 399, in get_raw_json
[optjournal] [2024-01-31 19:18:46]     response = self.get(url, user_agent_headers=user_agent_headers, params=params, proxy=proxy, timeout=timeout)
[optjournal] [2024-01-31 19:18:46]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/utils.py", line 103, in wrapper
[optjournal] [2024-01-31 19:18:46]     result = func(*args, **kwargs)
[optjournal] [2024-01-31 19:18:46]              ^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/data.py", line 348, in get
[optjournal] [2024-01-31 19:18:46]     cookie, crumb, strategy = self._get_cookie_and_crumb()
[optjournal] [2024-01-31 19:18:46]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/utils.py", line 103, in wrapper
[optjournal] [2024-01-31 19:18:46]     result = func(*args, **kwargs)
[optjournal] [2024-01-31 19:18:46]              ^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/data.py", line 324, in _get_cookie_and_crumb
[optjournal] [2024-01-31 19:18:46]     cookie, crumb = self._get_cookie_and_crumb_basic(proxy, timeout)
[optjournal] [2024-01-31 19:18:46]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/utils.py", line 103, in wrapper
[optjournal] [2024-01-31 19:18:46]     result = func(*args, **kwargs)
[optjournal] [2024-01-31 19:18:46]              ^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/data.py", line 213, in _get_cookie_and_crumb_basic
[optjournal] [2024-01-31 19:18:46]     cookie = self._get_cookie_basic(proxy, timeout)
[optjournal] [2024-01-31 19:18:46]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/data.py", line 156, in _get_cookie_basic
[optjournal] [2024-01-31 19:18:46]     self._cookie = self._load_cookie_basic()
[optjournal] [2024-01-31 19:18:46]                    ^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/data.py", line 142, in _load_cookie_basic
[optjournal] [2024-01-31 19:18:46]     cookie_dict = cache.get_cookie_cache().lookup('basic')
[optjournal] [2024-01-31 19:18:46]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/cache.py", line 369, in lookup
[optjournal] [2024-01-31 19:18:46]     self.initialise()
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/yfinance/cache.py", line 355, in initialise
[optjournal] [2024-01-31 19:18:46]     db.create_tables([_CookieSchema])
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3441, in create_tables
[optjournal] [2024-01-31 19:18:46]     model.create_table(**options)
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 6948, in create_table
[optjournal] [2024-01-31 19:18:46]     cls._schema.create_all(safe, **options)
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 6050, in create_all
[optjournal] [2024-01-31 19:18:46]     self.create_table(safe, **table_options)
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 5901, in create_table
[optjournal] [2024-01-31 19:18:46]     self.database.execute(self._create_table(safe=safe, **options))
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3260, in execute
[optjournal] [2024-01-31 19:18:46]     return self.execute_sql(sql, params)
[optjournal] [2024-01-31 19:18:46]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3250, in execute_sql
[optjournal] [2024-01-31 19:18:46]     with __exception_wrapper__:
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3020, in __exit__
[optjournal] [2024-01-31 19:18:46]     reraise(new_type, new_type(exc_value, *exc_args), traceback)
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 192, in reraise
[optjournal] [2024-01-31 19:18:46]     raise value.with_traceback(tb)
[optjournal] [2024-01-31 19:18:46]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3252, in execute_sql
[optjournal] [2024-01-31 19:18:46]     cursor.execute(sql, params or ())
[optjournal] [2024-01-31 19:18:46] peewee.OperationalError: disk I/O error

**Comment by ValueRaider** [comment]
> I tried to include "chmod -R 777 ." as a build command but that did not seem to work.

Probably the virtualisation interfering. Try fixing the cache first - it's reduces spam, and easier than coding a fix. Try [set_tz_cache_location](https://github.com/ranaroussi/yfinance#persistent-cache-store)

**Comment by pythoninoffice** [comment]
> > I tried to include "chmod -R 777 ." as a build command but that did not seem to work.
> 
> Probably the virtualisation interfering. Try fixing the cache first - it's reduces spam, and easier than coding a fix. Try [set_tz_cache_location](https://github.com/ranaroussi/yfinance#persistent-cache-store)

Thank you @ValueRaider. Tried that and it didn't work. Turned out it might have something to do with DO's virtual file system. No problem with the regular read/write permissions to the storage. However the "wal" mode of SQlite is not allowed.

I contacted DO support and they are currently looking into the issue. Will update here once I heard back.
