### ISSUE TITLE
base.py exception handling

### ISSUE THREAD

**Issue by gborrageiro** [ranaroussi/yfinance#195]
please can you add exception handling to Ticker.info() ?
some of the information is actually available, which would be handy to return, whilst some of it is unfortunately missing.

Example:

import pprint
  ...: import yfinance as yf
  ...: 
symbol = 'AIR.DE'
  ...: ticker = yf.Ticker(symbol)
  ...: 
# get stock info
  ...: print('\n%s info:' % symbol)
  ...: pprint.pprint(ticker.info)
  ...: 
AIR.DE info:
Traceback (most recent call last):
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-cde67c0544fb>", line 3, in <module>
    pprint.pprint(ticker.info)
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/yfinance/base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range

**Comment by ahemberger** [comment]
+1; trying to use this module and it keeps failing on me. The failure happens when pulling on .info; can I request that some error handling be installed to handle this gracefully?
