### ISSUE TITLE
f-string: unmatched '(' when importing yfinance

### ISSUE THREAD

**Issue by FX196** [ranaroussi/yfinance#2093]
### Describe bug

Syntax error in screener with Python 3.10. Error is coming from https://github.com/ranaroussi/yfinance/blob/main/yfinance/screener/screener.py#L101

### Simple code that reproduces your problem

```python
import yfinance
```
using Python 3.10

### Debug log
No debug logs but have stack trace of the import error
```
Traceback (most recent call last):
  File "/home/runner/work/.../libs.py", line 2, in <module>
    import yfinance as yf
  File "/home/runner/work/.../venv/lib/python3.10/site-packages/yfinance/__init__.py", line 30, in <module>
    from .screener.screener import Screener
  File "/home/runner/work/.../venv/lib/python3.10/site-packages/yfinance/screener/__init__.py", line 1, in <module>
    from .screener import Screener
  File "/home/runner/work/.../venv/lib/python3.10/site-packages/yfinance/screener/screener.py", line 101
    logger.error(f"Failed to get screener data for '{self._body.get('query', "query not set")}' reason: {e}")
                                                                              ^^^^^
SyntaxError: f-string: unmatched '('
Error: Process completed with exit code 1.
```

### `yfinance` version

0.2.45

### Python version

3.10

**Comment by sing-tam** [comment]
same issue here

**Comment by mrimahajan** [comment]
Can we take some action on this asap. This is impacting the daily production jobs for us.

**Comment by FX196** [comment]
> Can we take some action on this asap. This is impacting the daily production jobs for us.

@mrimahajan you can pin your version to the previous release by changing your `requirements.txt` to say `yfinance==0.2.44`. That's what I did to fix mine

**Comment by ValueRaider** [comment]
I'm confused how
> from .screener import Screener

is causing `Screener._fetch_and_parse()` to execute. I can't reproduce.

@ericpien

**Comment by fled-dev** [comment]
Same issue

**System Details**
- MacOS 15.1
- Python 3.11.9

**Comment by abdulmuhaiminmk** [comment]
> > Can we take some action on this asap. This is impacting the daily production jobs for us.
> 
> @mrimahajan you can pin your version to the previous release by changing your `requirements.txt` to say `yfinance==0.2.44`. That's what I did to fix mine

I solved the issues using jupyter notebook by pinned the previous version upon installing

'''!pip3 install yfinance==0.2.44'''

**Comment by abdulmuhaiminmk** [comment]
> > Can we take some action on this asap. This is impacting the daily production jobs for us.
> 
> @mrimahajan you can pin your version to the previous release by changing your `requirements.txt` to say `yfinance==0.2.44`. That's what I did to fix mine

I solved the issues using jupyter notebook by pinned the previous version upon installing `!pip3 install yfinance==0.2.44`

**Comment by mm3509** [comment]
Same problem here, and this bug arises during import.

**Comment by srepollock** [comment]
The fix has been merged in. Is a new release being created?

**Comment by ValueRaider** [comment]
Fix merged and released.

Is there a simple action/workflow we can add to avoid a repeat? Ideally not running all the unit tests because that involves dozens of fetches.

**Comment by vwbusguy** [comment]
The updated release fixed this for our builds.  Thanks!
