### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by dannyvw-on-github** [ranaroussi/yfinance#213]
Hi,
I've tried to use the module via a proxy, but it didn't work. After inspecting the code I noticed the following:
I use after importing and setting proxies:
```python
msft = yf.Ticker("MSFT")
# get stock info
msft.get_info(proxy=proxies)
```
In base.py
```python
def get_info(self, proxy=None, as_dict=False, *args, **kwargs):
    self._get_fundamentals(proxy)   #dvw this would fix it: self._get_fundamentals(proxy=proxy)
    …
```
when you then go to that function
```python
def _get_fundamentals(self, kind=None, proxy=None):
    …
```
the proxy is not set correctly. I have put in comment the correction that works for me but I get errors later on then. 

If you want to test it apart (no classes and for illustration), you can try this:
```python
def get_fundamentals(kind=None, proxy=None):
    print(f"proxy is {proxy}")

def get_info(proxy=None, as_dict=False, *args, **kwargs):
    print(f"In get_info is proxy equal to {proxy}")
    get_fundamentals(proxy)
    # statement below corrects this
    #get_fundamentals(proxy=proxy)

get_info(proxy='testProxy')
```

**Comment by psabalot** [comment]
Hi everyone,

I agree with the previous post.
The "_get_fundamentals(proxy=proxy)" instead of "_get_fundamentals(proxy)" does the trick of extending yfinance use over proxies and correcting this bug. It should be extended to all _get_calendar, _get_earnings... functions in the base.py file which suffer the same problem.

I also hase to report that the use of pd.read_html in the _get_fundamentals (base.py) function declaration is not compatible with proxy use, but the following trick works fine :
holders = _pd.read_html(_requests.get(url=url, proxies=proxy).text).

Apart from these two corrections, yfinance is quite manageable through proxies.

Best,
Paul

**Comment by footfalcon** [comment]
Hi, sorry for the basic question, but how do you specify a proxy with yfinance? Do you just specify the proxy IP as a string? I tried this but it didn't work:

```
yf.download(
        tickers='AAPL', 
        period='5d', 
        interval='60d',
        proxy='85.10.219.98',
        auto_adjust=True
    )
```

Thanks!

**Comment by psabalot** [comment]
Specifying the proxy with a string, like you do, should work just fine.
Your code works on my side with my own proxy string (removing your interval condition which does not allow 60d as a licit value, though).

**Comment by footfalcon** [comment]
@psabalot Thanks for the reply. The '60d' interval was a typo (apologies) but did not affect my code (which had it correctly specified and '60m'). I am using proxies from https://free-proxy-list.net/ and have tried several with my code above but it still generates an error. I have tested the proxies with requests.get() on other websites and they work fine. Am I maybe missing something in my yfinance installation (I used `conda install -c ranaroussi yfinance`)? Here is my error message in case you are able to decipher anything -- thanks!

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    self._tunnel()
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/http/client.py", line 921, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 503 unknown method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/AAPL?range=5d&interval=1d&includePrePost=False&events=div%2Csplits (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 unknown method')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/yfinance/base.py", line 150, in history
    data = _requests.get(url=url, params=params, proxies=proxy)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Volumes/Anaconda/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/AAPL?range=5d&interval=1d&includePrePost=False&events=div%2Csplits (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 unknown method')))
```
