### ISSUE TITLE
KeyError exception when getting APPL ticker info

### ISSUE THREAD

**Issue by slmnewton** [ranaroussi/yfinance#264]
>>> import yfinance as yf
>>> 
>>> 
>>> appl = yf.Ticker('APPL')
>>> appl
yfinance.Ticker object <APPL>
>>> 
>>> appl.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/service/pidbot/venv/lib64/python3.6/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/service/pidbot/venv/lib64/python3.6/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/usr/service/pidbot/venv/lib64/python3.6/site-packages/yfinance/base.py", line 318, in _get_fundamentals
    self._info['regularMarketPrice'] = self._info['regularMarketOpen']
KeyError: 'regularMarketOpen'

**Comment by AcudoDev** [comment]
Are you trying to access to Apple data ? In this case the Apple ticker is AAPL not APPL.

**Comment by slmnewton** [comment]
My mistake. Thank you for the quick response.
