### ISSUE TITLE
Getting index out of range exception when accessing Morgan Stanley stock info

### ISSUE THREAD

**Issue by slmnewton** [ranaroussi/yfinance#268]
>>> import yfinance as yf
>>> 
>>> ms = yf.Ticker('MS')
>>> ms
yfinance.Ticker object <MS>
>>> 
>>> ms.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/service/pidbot/venv/lib64/python3.6/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/service/pidbot/venv/lib64/python3.6/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/usr/service/pidbot/venv/lib64/python3.6/site-packages/yfinance/base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range

**Comment by rodrigobercini** [comment]
The base code needs an error handler for cases where there are no institutional holders. There are some PRs that could solve this issue, but while they are not merged, you can install my fork (don't forget to uninstall yfinance and restart the runtime):
pip uninstall yfinance
pip install git+https://github.com/rodrigobercini/yfinance.git

I've just tested for MS and it's working fine. Cheers!

**Comment by jacobhal** [comment]
@rodrigobercini I will use your forked version for now, thank you!

For others who are using Heroku to deploy, simply remove "yfinance==0.1.54" from requirements.txt and add "git+https://github.com/rodrigobercini/yfinance.git"
