### ISSUE TITLE
Institution list index out of range, a test scenario

### ISSUE THREAD

**Issue by dmwesterhoff** [ranaroussi/yfinance#274]
```
>>> import yfinance
>>> t=yfinance.Ticker('BRK-B')
>>> t.info
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/westerhoff/Developer/lucrum/.venv/lib/python3.7/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/Users/westerhoff/Developer/lucrum/.venv/lib/python3.7/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/Users/westerhoff/Developer/lucrum/.venv/lib/python3.7/site-packages/yfinance/base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range
```

**Comment by rodrigobercini** [comment]
The base code needs an error handler for cases where there are no institutional holders. There are some PRs that could solve this issue, but while they are not merged, you can install my fork (don't forget to uninstall yfinance and restart the runtime):
pip uninstall yfinance
pip install git+https://github.com/rodrigobercini/yfinance.git

I've just tested for BRK-B and it's working fine. Cheers!
