### ISSUE TITLE
Test scenario - KeyError: "['maxAge'] not found in axis"

### ISSUE THREAD

**Issue by vineet-karkera-vgh** [ranaroussi/yfinance#275]
Following fork installed; It worked great for the "index out of range" issue that occurred for tickers with no institution holdings.

pip uninstall yfinance
pip install git+https://github.com/rodrigobercini/yfinance.git

But, noticed a new issue, illustrated with code below:
import yfinance as yf
ticker = yf.Ticker('TDI.AX')
print(ticker.info)

**Error:** 
raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['maxAge'] not found in axis"

**Complete Log:**
 runfile('C:/Users/***/.spyder-py3/TradingProject/testing.py', wdir='C:/Users/Vineet/.spyder-py3/TradingProject')
Traceback (most recent call last):

  File "C:\Users\***\.spyder-py3\TradingProject\testing.py", line 12, in <module>
    print(ticker.info)

  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()

  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\base.py", line 421, in get_info
    self._get_fundamentals(proxy)

  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\base.py", line 371, in _get_fundamentals
    key[0]['yearly'] = cleanup(data[item][key[2]])

  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\base.py", line 252, in cleanup
    df = _pd.DataFrame(data).drop(columns=['maxAge'])

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3997, in drop
    errors=errors,

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3936, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3970, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 5018, in drop
    raise KeyError(f"{labels[mask]} not found in axis")

KeyError: "['maxAge'] not found in axis"

**Comment by rodrigobercini** [comment]
Hey there, I've applied the fixes mentioned in https://github.com/ranaroussi/yfinance/pull/174 to my fork. I just tested and it seems to be working. Try reinstalling my fork.

![Screenshot_1](https://user-images.githubusercontent.com/18664907/80424642-87af6400-88b8-11ea-885b-44a916ba4efe.jpg)

**Comment by vineet-karkera-vgh** [comment]
Sweet! Thank you. Fix tested and works great. Great work on this initiative btw. Cheers.
