### ISSUE TITLE
KeyError: 'regularMarketOpen' - version 0.1.54

### ISSUE THREAD

**Issue by milkywade** [ranaroussi/yfinance#333]
Hi Ran,

got into this apparently old / recurrent problem.

Many thanks in advance

```
ERROR:root:Traceback (most recent call last):
  File "test3.py", line 140, in update_stocks_data
    stock_info = yf.Ticker(stock).info
  File "C:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "C:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\yfinance\base.py", line 418, in get_info
    self._get_fundamentals(proxy)
  File "C:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\yfinance\base.py", line 321, in _get_fundamentals
    self._info['regularMarketPrice'] = self._info['regularMarketOpen']
KeyError: 'regularMarketOpen'
```
using python 3.7.7 pandas 1.0.3 numpy 1.18.1 on windows 10 64b with miniconda 3
happens with several european stocks such as EI.PA

**Comment by michalkonik** [comment]
Did you resolve the issue?
I am facing the same error for multiple requests.

**Comment by aaltmann** [comment]
Same issue.

**Comment by ValueRaider** [comment]
@aaltmann create a new issue.
