### ISSUE TITLE
Unable to get Fundamental Details . Index error . Code Attached

### ISSUE THREAD

**Issue by drshaktiyadav** [ranaroussi/yfinance#342]
python3                                                                    Python 3.8.3 (default, May 14 2020, 11:03:12)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
>>> s=yf.Ticker("TATAMOTORS.NS")
>>> print(s.info())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.8/dist-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.8/dist-packages/yfinance/base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range
>>>

**Comment by rodrigobercini** [comment]
Hey there, you can try applying the fixes described in this PR https://github.com/ranaroussi/yfinance/pull/179.
