### ISSUE TITLE
MGFF11.SA don't return right quote

### ISSUE THREAD

**Issue by HackEduca** [ranaroussi/yfinance#346]
Hi,  I am trying to get data from MGFF11.SA ticker and I receive the following return:

Appreciate if you can help. 

Thanks!

```
Traceback (most recent call last):
  File "ya.py", line 6, in <module>
    print(msft.info)
  File "C:\Users\Sobreie\Downloads\WPy64-3830\python-3.8.3.amd64\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "C:\Users\Sobreie\Downloads\WPy64-3830\python-3.8.3.amd64\lib\site-packages\yfinance\base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "C:\Users\Sobreie\Downloads\WPy64-3830\python-3.8.3.amd64\lib\site-packages\yfinance\base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range
```

**Comment by rodrigobercini** [comment]
Hey there, try applying the fixes described in PR #179.

Just be aware that that fix returns inconsistent data for non-US tickers.
