### ISSUE TITLE
IndexError: list index out of range (similar to #208)

### ISSUE THREAD

**Issue by siavashadpey** [ranaroussi/yfinance#352]
```python
t = yf.Ticker("XEF.TO").info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/yfinance/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/ubuntu/yfinance/yfinance/base.py", line 416, in get_info
    self._get_fundamentals(proxy)
  File "/home/ubuntu/yfinance/yfinance/base.py", line 305, in _get_fundamentals
    s[s.index == 'ratingYear']['Value'].values[0],
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I got this issue by cloning the master branch with the latest commit being 9cdda84. The issue is similar to #208. Simply checking if the entry exists before accessing it would fix this bug.

**Comment by siavashadpey** [comment]
PR #354 should fix this. However the code is failing the codefactor check. I didn't have a chance to check if it's because of my code changes or something else.
