### ISSUE TITLE
Exception in thread Thread-6: getting this error for symbols today... sometimes it works for the same symbol, else this message

### ISSUE THREAD

**Issue by swankyshahir** [ranaroussi/yfinance#360]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/usr/local/lib/python3.6/dist-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/usr/local/lib/python3.6/dist-packages/yfinance/base.py", line 155, in history
    data = data.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by swankyshahir** [comment]
error reproduced from colab jupyter notebook

**Comment by sonicxml** [comment]
I have also been getting the same error. I assumed it was because Yahoo Finance probably changed their query endpoint

**Comment by swankyshahir** [comment]
sonicxml ..... i installed from another fork also to see if it helps (pip install git+https://github.com/rodrigobercini/yfinance.git) still the same error so it appears fundamental to yfinance.... any old forks can help ?

**Comment by MLauer91** [comment]
Can confirm this is an issue too. It seems to appear and not appear for the same symbol. For instance, I tried 'SPY' twice with the first time producing the error and the second time not.

**Comment by swankyshahir** [comment]
AntonioHidalgoLanda wrapper works issue # 318 . However, i hope yfinance addresses this issue. plenty of thanks to ranaroussi though.... as i am totally dependant on yfinance

**Comment by crdcj** [comment]
I am getting something similiar hier too:

ativos = yf.download(tickers=list_tickers[0:10].tolist(), threads = False,period='1y')

  File "C:\Users\Vostok\anaconda3\lib\site-packages\yfinance\multi.py", line 103, in download
    back_adjust=back_adjust, rounding=rounding)

  File "C:\Users\Vostok\anaconda3\lib\site-packages\yfinance\multi.py", line 182, in _download_one
    rounding=rounding, many=True)

  File "C:\Users\Vostok\anaconda3\lib\site-packages\yfinance\base.py", line 155, in history
    data = data.json()

  File "C:\Users\Vostok\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)

  File "C:\Users\Vostok\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)

  File "C:\Users\Vostok\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\Vostok\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by swanandM** [comment]
See the same issue, from last 3-4 days

---> 12     data = name.history(period=period, interval=interval)

/usr/local/lib/python3.5/dist-packages/yfinance/base.py in history(self, period, interval, start, end, prepost, actions, auto_adjust, back_adjust, proxy, rounding, tz, **kwargs)
    153                                "Our engineers are working quickly to resolve "
    154                                "the issue. Thank you for your patience.")
--> 155         data = data.json()
    156 
    157         # Work with errors

/usr/local/lib/python3.5/dist-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

/usr/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder

/usr/lib/python3.5/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

**Comment by igor555** [comment]
same issues with SPYDER:

Traceback (most recent call last):

  File "C:\xxxxx\watchlist_one_function.py", line 338, in <module>
    get_daily_watchlist_results()

  File "C:\xxxxx\watchlist_one_function.py", line 85, in get_daily_watchlist_results
    daily_ticker_hist = yf_data.history(period="max", interval="1d")

  File "C:\Users\xxxxx\Anaconda3\lib\site-packages\yfinance\base.py", line 155, in history
    data = data.json()

  File "C:\Users\xxxxx\Anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)

  File "C:\Users\xxxxx\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)

  File "C:\Users\xxxxx\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\xxxxx\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by cayman2578** [comment]
Did you find the reason of that? I'm getting this error now

**Comment by igor555** [comment]
@cayman2578 getting the same. I think Yahoo is having some issues

**Comment by cayman2578** [comment]
> @cayman2578 getting the same. I think Yahoo is having some issues

upgrade to 0.1.62

**Comment by cayman2578** [comment]
> > @cayman2578 getting the same. I think Yahoo is having some issues
> 
> upgrade to 0.1.62

I mean yfinance

**Comment by igor555** [comment]
@cayman2578 how do i upgrade? I am running it in Spyder

**Comment by cayman2578** [comment]
> @cayman2578 how do i upgrade? I am running it in Spyder

pip install yfinance --upgrade --no-cache-dir

https://pypi.org/project/yfinance/

It works

**Comment by igor555** [comment]
I had to do this

py -m pip install --upgrade yfinance

https://docs.python.org/3/installing/index.html

**Comment by apolobezerra** [comment]
It doesn't work for me even with the 0.1.63 version

**Comment by jprm610** [comment]
I'm having the same issue even with the 0.1.63 version

**Comment by yannkGit** [comment]
Same issue here. I also upgrated to version 0.1.63

**Comment by dprata00** [comment]
I updated my anaconda and the yfinance package. It solved my problem
