### ISSUE TITLE
Option expiration dates randomly missing

### ISSUE THREAD

**Issue by andr3w321** [ranaroussi/yfinance#469]
I'm getting random option expiration date cannot be found errors. I can't consistently reproduce the bug. It happens randomly.

Code
```
sp500_tickers = get_sp500_tickers()
for ticker in sp500_tickers:
    try:
        option_dates = yf.Ticker(ticker).options
    except IndexError:
        print("No options found for {}".format(ticker))
        continue

    for option_date in option_dates:
        print(ticker, option_date)
        time.sleep(0.1)
        opt = yf.Ticker(ticker).option_chain(option_date)
```

Error
```
GILD 2020-10-01
GILD 2020-10-08
GILD 2020-10-15
GILD 2020-10-22
GILD 2020-10-29
GILD 2020-11-05
GILD 2020-11-12
Traceback (most recent call last):
  File "import_options.py", line 128, in <module>
    import_options(ticker, args.pst_approx)
  File "import_options.py", line 93, in import_options
    opt = yf.Ticker(ticker).option_chain(option_date)
  File "/lib/python3.8/site-packages/yfinance/ticker.py", line 94, in option_chain
    raise ValueError(
ValueError: Expiration `2020-11-12` cannot be found. Available expiration are: [2020-10-01, 2020-10-08, 2020-10-15, 2020-10-22, 2020-10-29, 2020-11-05, 2020-11-19, 2020-12-17, 2021-01-14, 2021-02-18, 2021-03-18, 2021-05-20, 2021-06-17, 2022-01-20, 2022-06-16, 2023-01-19]
```

**Comment by andr3w321** [comment]
It seems the error is that ticker options' url often displays the wrong expiration date.

https://query1.finance.yahoo.com/v7/finance/options/GILD?formatted=true&crumb=hHQibbDPMTN&lang=en-US&region=US&date=1602806400&corsDomain=finance.yahoo.com

For now, I wrapped the whole thing in a function and catch the error and retry 3 times.

```
def import_options(ticker, retries=3):
    try:
        option_dates = yf.Ticker(ticker).options
    except IndexError:
        print("No options found for {}".format(ticker))
        return

    for option_date in option_dates:
        print(ticker, option_date)
        time.sleep(0.1)
        try:
            opt = yf.Ticker(ticker).option_chain(option_date)
        except:
            time.sleep(0.1)
            print("ERROR getting option date for {}, {} retries remaining on all options...".format(ticker, retries))
            if retries > 0:
                retries -= 1
                import_options(ticker, retries)
            else:
                raise ValueError("Failed to get options for {}".format(ticker))
        else:
            save_option(ticker, option_date, opt.calls, 1)
            save_option(ticker, option_date, opt.puts, 0)
```

Alternatively, line ~93 of https://github.com/ranaroussi/yfinance/blob/master/yfinance/ticker.py could be rewritten to retry the option chain once before raising an error

```
    def option_chain(self, date=None, proxy=None, tz=None):
        if date is None:
            options = self._download_options(proxy=proxy)
        else:
            if not self._expirations:
                self._download_options()
            if date not in self._expirations:
                self._download_options()
                if date not in self._expirations:
                    raise ValueError(
                        "Expiration `%s` cannot be found. "
                        "Available expiration are: [%s]" % (
                            date, ', '.join(self._expirations)))
            date = self._expirations[date]
            options = self._download_options(date, proxy=proxy)

        return _namedtuple('Options', ['calls', 'puts'])(**{
            "calls": self._options2df(options['calls'], tz=tz),
            "puts": self._options2df(options['puts'], tz=tz)
        })

```
