### ISSUE TITLE
code gets stuck at a certain row even if changing the ticker name

### ISSUE THREAD

**Issue by mariafinance** [ranaroussi/yfinance#473]
Hi guys, I 've made a code that gets the tickers from an excel sheet (''C'' column ) and then finding the market caps but when I try it I get this error: And I tried to see if the code works for certain rows and it does, it doesn't work only at row 57!!! I changed the ticker name and again same problem!!! What is wrong with the code? 
`market_cap_data= web.get_quote_yahoo(tickers_list[57])['marketCap']`

THIS IS MY CODE: 
```
import pandas as pd
import numpy as np
from pandas import ExcelWriter
from pandas import ExcelFile
from pandas import DataFrame
from openpyxl import Workbook

from openpyxl import load_workbook
wb = load_workbook('/Users/maria/Job/Python/Ws.xlsx')  # Work Book
ws = wb['Sheet2']  # Work Sheet
column = ws['C']  # Column
tickers_list = [column[x].value for x in range(len(column))]

print(*tickers_list, sep='\n')  #επιβεβαιώνω ότι λειτουργεί σωστά και τυπώνει τα tickers από excel
print(len(tickers_list))  #επιβεβαιώνω ότι το μέγεθος των στοιχείων είναι σωστό

import yfinance as yf
#extract the marketcaps
import pandas_datareader as web
market_cap_data= pd.DataFrame()
market_cap_data= web.get_quote_yahoo(tickers_list[57])['marketCap']
print(market_cap_data)
```
#THIS IS THE ERROR THAT I GET
Traceback (most recent call last):
  File "/Users/maria/Job/Python/marketcap.py", line 21, in <module>
    market_cap_data= web.get_quote_yahoo(tickers_list[57])['marketCap']
  File "/Users/maria/PycharmProjects/STOCKS/venv/lib/python3.8/site-packages/pandas_datareader/data.py", line 102, in get_quote_yahoo
    return YahooQuotesReader(*args, **kwargs).read()
  File "/Users/maria/PycharmProjects/STOCKS/venv/lib/python3.8/site-packages/pandas_datareader/yahoo/quotes.py", line 26, in read
    return self._read_one_data(self.url, self.params(self.symbols))
  File "/Users/maria/PycharmProjects/STOCKS/venv/lib/python3.8/site-packages/pandas_datareader/base.py", line 112, in _read_one_data
    return self._read_lines(out)
  File "/Users/maria/PycharmProjects/STOCKS/venv/lib/python3.8/site-packages/pandas_datareader/yahoo/quotes.py", line 43, in _read_lines
    data = json.loads(out.read())["quoteResponse"]["result"][0]
IndexError: list index out of range

**Comment by ValueRaider** [comment]
That error is in `pandas datareader`, nothing to do with `yfinance`
