### ISSUE TITLE
IndexError: list index out of range (similar to #352)

### ISSUE THREAD

**Issue by marketemp** [ranaroussi/yfinance#485]
reading issue 352, it appears the issue is fixed by #354, but I am running the current latest 0.1.55 and getting:

yft = yf.Ticker('AAA').info

Traceback (most recent call last):
  File "imac.py", line 17, in <module>
    yft = yf.Ticker('AAA').info
  File "/Users/steve/PycharmProjects/marketemp/venv/lib/python3.7/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/Users/steve/PycharmProjects/marketemp/venv/lib/python3.7/site-packages/yfinance/base.py", line 446, in get_info
    self._get_fundamentals(proxy)
  File "/Users/steve/PycharmProjects/marketemp/venv/lib/python3.7/site-packages/yfinance/base.py", line 326, in _get_fundamentals
    s[s.index == 'ratingYear']['Value'].values[0],
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ValueRaider** [comment]
That error was from the old scraping code failing, long gone.
