### ISSUE TITLE
Error upon pulling ISIN for "HDFC.BO"

### ISSUE THREAD

**Issue by lokeshbhatt** [ranaroussi/yfinance#512]
Hi Ran,
yfinance is a great work. I have started using it from today's midnight (IST).
While it works for most tickers, it comes back broken for  "HDFC.BO".
Is there something you can optimize in library or there is some problem catching unexpected from your data source ?

Here is a copy paste of error from IDLE prompt,

import yfinance as yf

msft=yf.Ticker("HDFC.BO")

msft.isin()
Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    msft.isin()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\yfinance\ticker.py", line 110, in isin
    return self.get_isin()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\yfinance\base.py", line 526, in get_isin
    self.get_info(proxy=proxy)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\yfinance\base.py", line 446, in get_info
    self._get_fundamentals(proxy)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\yfinance\base.py", line 285, in _get_fundamentals
    holders = _pd.read_html(url)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\html.py", line 1094, in read_html
    displayed_only=displayed_only)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\html.py", line 916, in _parse
    raise_with_traceback(retained)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\compat\__init__.py", line 420, in raise_with_traceback
    raise exc.with_traceback(traceback)
ValueError: No tables found

**Comment by jamesprinc3** [comment]
Seems to be failing on this line: https://github.com/ranaroussi/yfinance/blob/6e52c83d9affc7a8a6a209f83d7482c64b24d67b/yfinance/base.py#L285

Because the URL at that stage points to this page: https://finance.yahoo.com/quote/HDFC.BO/holders?p=HDFC.BO which has no information on it. One suggestion would be to wrap a try/catch around that line, similar to what is done here: https://github.com/ranaroussi/yfinance/blob/6e52c83d9affc7a8a6a209f83d7482c64b24d67b/yfinance/base.py#L342

**Comment by lokeshbhatt** [comment]
Yes i can see there us no table data at https://finance.yahoo.com/quote/HDFC.BO/holders?p=HDFC.BO.

But what if my point of interest is only last day close price?, this much is available in page pointed (refer attached snapshot).

Is there a way, i can pull displayed price ?

![image](https://user-images.githubusercontent.com/30107139/100021200-1e201580-2e07-11eb-8f23-908dd7947fad.png)

**Comment by jamesprinc3** [comment]
You can use the `history` function to find out that information. e.g.
```
yf.Ticker("HDFC.BO").history()
```

**Comment by lokeshbhatt** [comment]
>>> import yfinance
>>> yf.Ticker("HDFC.BO").history()
Traceback (most recent call last):
  File "<pyshell#34>", line 1, in <module>
    yf.Ticker("HDFC.BO").history()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\yfinance\base.py", line 223, in history
    dividends, splits = utils.parse_actions(data["chart"]["result"][0], tz)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\yfinance\utils.py", line 141, in parse_actions
    dividends = _pd.DataFrame(columns=["Dividends"])
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\internals\construction.py", line 197, in init_dict
    arrays.loc[missing] = [val] * missing.sum()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\indexing.py", line 189, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\indexing.py", line 175, in _get_setitem_indexer
    return self._convert_to_indexer(key, is_setter=True)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\indexing.py", line 1310, in _convert_to_indexer
    return labels.get_loc(obj)
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 110, in pandas._libs.index.IndexEngine.get_loc
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\base.py", line 57, in __str__
    return self.__unicode__()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\series.py", line 1377, in __unicode__
    width, height = get_terminal_size()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\formats\terminal.py", line 35, in get_terminal_size
    return shutil.get_terminal_size()
  File "C:\Users\LokeshBhatt\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 1062, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'

**Comment by jamesprinc3** [comment]
It's not immediately clear to me what the issue is there. I'm running on a Mac with Python 3.9, Pandas==1.1.4, which could be the difference?

Does this work for you using a different ticker?
