### ISSUE TITLE
Can't get all Amazon stock data and not any Amazon recommendations

### ISSUE THREAD

**Issue by krikru** [ranaroussi/yfinance#528]
When I do

```
import yfinance as yf
from tabulate import tabulate

ticker = yf.Ticker('AMZ')
history = ticker.history(period="max", interval='1d')
print(tabulate(history, headers='keys', tablefmt='psql'))
```

the last eight entries of the printed table looks like this:

```
| 2018-01-25 00:00:00 | 1094    | 1106     | 1084     | 1096     |     5159 |           0 |              0 |
| 2018-01-26 00:00:00 | 1110    | 1128     | 1108     | 1124     |     6044 |           0 |              0 |
| 2018-01-29 00:00:00 | 1138    | 1150     | 1130     | 1148     |    13659 |           0 |              0 |
| 2018-01-30 00:00:00 | 1144    | 1152.18  | 1116.01  | 1149.06  |    10004 |           0 |              0 |
| 2018-05-22 00:00:00 |    1.4  |    1.49  |    1.4   |    1.42  |    42899 |           0 |              0 |
| 2018-05-23 00:00:00 |    1.45 |    1.48  |    1.41  |    1.41  |     8511 |           0 |              0 |
| 2018-05-24 00:00:00 |    1.46 |    1.46  |    1.42  |    1.43  |    11780 |           0 |              0 |
| 2018-05-25 00:00:00 |    1.41 |    1.44  |    1.33  |    1.33  |    30363 |           0 |              0 |
+---------------------+---------+----------+----------+----------+----------+-------------+----------------+
```

I.e., there isn't any data between 2018-01-30 and 2018-05-22 (but there seems to have been a severe stock crash), and no data after 2018-05-25.

Besides, when I do

```
import yfinance as yf

ticker = yf.Ticker('AMZ')
recommendations = ticker.recommendations
```

the script crashes with the following traceback:

```
Traceback (most recent call last):
  File "D:/work/programs/stocks/stocks.py", line 4, in <module>
    recommendations = ticker.recommendations
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\yfinance\ticker.py", line 146, in recommendations
    return self.get_recommendations()
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\yfinance\base.py", line 409, in get_recommendations
    self._get_fundamentals(proxy)
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\yfinance\base.py", line 340, in _get_fundamentals
    self._info['regularMarketPrice'] = self._info['regularMarketOpen']
KeyError: 'regularMarketOpen'
```

**Comment by kelanwilks** [comment]
AMZ is in an international market which I don't think is supported by yfinance. Try AMZN

**Comment by krikru** [comment]
@kelanwilks Thanks—I also realized that I had used the wrong symbol—when I used AMZN instead it worked much better! However, I think it's a bit strange that I get any data at all if yfinance is not supposed to support AMZ, isn't it?

**Comment by kelanwilks** [comment]
@krikru So if you check out the yahoo finance page here https://finance.yahoo.com/quote/AMZ?p=AMZ
it looks like it has minimal info, and the info it has is delayed by a lot (checkout price history from a few years back). This framework (from what I understand) is simply scraping data from yahoo, so that is probably what you're seeing.
