### ISSUE TITLE
ValueError when calling the history method

### ISSUE THREAD

**Issue by krikru** [ranaroussi/yfinance#536]
When I do

```
import yfinance as yf

ticker = yf.Ticker('DIT')
ticker.history(period=None, start='2020-11-06', end='2020-12-23', interval='60m', prepost=True)
```

I get the following output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\yfinance\base.py", line 226, in history
    df = _pd.concat([quotes, dividends, splits], axis=1, sort=True)
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\pandas\core\reshape\concat.py", line 287, in concat
    return op.get_result()
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\pandas\core\reshape\concat.py", line 502, in get_result
    new_data = concatenate_block_managers(
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\pandas\core\internals\concat.py", line 84, in concatenate_block_managers
    return BlockManager(blocks, axes)
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\pandas\core\internals\managers.py", line 149, in __init__
    self._verify_integrity()
  File "D:\ProgramData\Miniconda3\envs\stocks\lib\site-packages\pandas\core\internals\managers.py", line 326, in _verify_integrity
    raise construction_error(tot_items, block.shape[1:], self.axes)
ValueError: Shape of passed values is (76, 7), indices imply (74, 7)
```

Any start date before 2020-11-06 (and after 2018-12-23, since that is more than 730 days ago) also seems to generate a corresponding error.

I'm using python 3.8.5 and yfinance 0.1.55.

**Comment by krikru** [comment]
And now it just seems to work again. Just like that. Weird.

**Comment by krikru** [comment]
When I try the same thing now, I'm getting the output

```
                                Open       High        Low      Close  Volume  Dividends  Stock Splits
Datetime
2020-11-05 09:30:00-05:00        NaN        NaN        NaN        NaN     NaN       0.18             0
2020-11-09 09:30:00-05:00  64.500000  64.500000  64.500000  64.500000     0.0       0.00             0
2020-11-09 10:30:00-05:00  64.500000  64.500000  64.500000  64.500000    41.0       0.00             0
2020-11-09 13:30:00-05:00  65.974998  65.974998  65.974998  65.974998    60.0       0.00             0
2020-11-10 09:30:00-05:00  70.029999  71.385597  67.732201  67.732201   582.0       0.00             0
...                              ...        ...        ...        ...     ...        ...           ...
2020-12-17 14:30:00-05:00  91.634598  91.634598  91.629997  91.629997   204.0       0.00             0
2020-12-17 15:30:00-05:00  91.629997  91.870003  91.629997  91.870003   142.0       0.00             0
2020-12-18 14:30:00-05:00  90.000000  90.050003  90.000000  90.000000   189.0       0.00             0
2020-12-18 15:30:00-05:00  90.000000  90.000000  90.000000  90.000000   150.0       0.00             0
2020-12-18 16:00:00-05:00  90.000000  90.000000  90.000000  90.000000   107.0       0.00             0

[73 rows x 7 columns]
```

Should I get the value `NaN` for some of the columns? Is this a feature or a bug? If it is a feature, what does it mean that the value is NaN?

**Comment by simonvdv** [comment]
Check on Yahoo! Finance itself. For the same search pattern, you'll get the same result (getting the 2020-11-05 dividend, in an extra row, same as you'll have the same behavior for any dividends and stock splits on other days).

This is standard Yahoo! Finance behavior (you can get rid of those by setting `actions=False` in you `history` call, but you'll still get an empty row for that index (something that should be fixed, my intuition being actions are collected and then discarded by yfinance, which is an extra step).

**Comment by krikru** [comment]
What do you mean by "for the same search pattern" on Yahoo! Finance, how do I use search patterns there? Is it possible to get the same data in tabulated form on the web page?

**Comment by simonvdv** [comment]
Yep, all in all, yfinance work as a wrapper for Yahoo! Finance queries!

For any stock, you can display the historical data in the "historical" tab, you get an url like this one:
`https://finance.yahoo.com/quote/AAPL/history?period1=1577564220&period2=1609186620&interval=1wk&filter=history&frequency=1wk&includeAdjustedClose=true`

You can copy all params and endpoints from yfinance if you fancy...

**Comment by ValueRaider** [comment]
Problem should be gone now because this line
```
df = _pd.concat([quotes, dividends, splits], axis=1, sort=True)
```
is replaced with smarter logic.
