### ISSUE TITLE
"Yahoo Finance is currently down" error

### ISSUE THREAD

**Issue by jkovach89** [ranaroussi/yfinance#578]
Receiving the following when trying to pull a large list of stock symbols with the following code:

Code:

`return yf.download(sym_list, start=date, end=end, interval=ivl, group_by='ticker')`

Error:

Exception in thread Thread-994:
Traceback (most recent call last):
  File "/Users/jkovach/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/jkovach/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jkovach/opt/anaconda3/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Users/jkovach/opt/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/Users/jkovach/opt/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/Users/jkovach/opt/anaconda3/lib/python3.7/site-packages/yfinance/base.py", line 152, in history
    raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***
Our engineers are working quickly to resolve the issue. Thank you for your patience.

Is there some way to handle this exception?

**Comment by beglitis** [comment]
See this

https://github.com/ranaroussi/yfinance/issues/445

**Comment by jkovach89** [comment]
Thanks for that. I actually updated my requests and urllib packages and that seems to have fixed the issue.

**Comment by beglitis** [comment]
> Thanks for that. I actually updated my requests and urllib packages and that seems to have fixed the issue.

Great!
