### ISSUE TITLE
error message while trying to get ETF Prices 

### ISSUE THREAD

**Issue by Jacques2101** [ranaroussi/yfinance#592]
hi, 
my code is simple :
```
import pandas as pd
import yfinance as yf

tickers = "XLP XLU XLV XLY XME XOP XPH XRT XSD XSW XTN"

data = yf.download(
    tickers=tickers,
    start='2000-01-01',
    end='2021-02-11',
    group_by="ticker",
    threads=True,
)
data
```

but I get an error message:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/site-packages/yfinance/multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/site-packages/yfinance/multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/site-packages/yfinance/base.py", line 155, in history
    data = data.json()
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jacques/opt/anaconda3/envs/data/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[**********************45%                       ]  5 of 11 completed
```
Then the code is blocked. 
Any ideas ?

**Comment by beglitis** [comment]
See this

https://github.com/ranaroussi/yfinance/issues/591

**Comment by ValueRaider** [comment]
Still happening?
