### ISSUE TITLE
Error when getting ticker info for 'CTEC'

### ISSUE THREAD

**Issue by nabelekt** [ranaroussi/yfinance#594]
This:
```
import yfinance as yf

ticker_data = yf.Ticker('CTEC')
ticker_data.info
```

Results in this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yfinance/base.py", line 446, in get_info
    self._get_fundamentals(proxy)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yfinance/base.py", line 326, in _get_fundamentals
    s[s.index == 'ratingYear']['Value'].values[0],
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Any ideas? It must be something unique to CTEC. All other ETF tickers I try work fine.

**Comment by jfgingras** [comment]
That's because the ticker CTEC doesn't have ESG Score information. Sometimes, the ESG Score place holder is there but is empty (I check that with a other ETF in clean energy). But in this case, the place holder is missing. This lead the library to crash.

Some "sanity check" should be added to the librairy. There's little you can do except to modify the code to add those validations or wait for someone to make a Pull Request.
