### ISSUE TITLE
Ticker HTOO - KeyError: "['maxAge'] not found in axis"

### ISSUE THREAD

**Issue by kucharskim** [ranaroussi/yfinance#599]
```
(yfinance-env) $ python
Python 3.8.7 (default, Feb 13 2021, 12:59:14)
[Clang 10.0.1 ] on openbsd6
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import yfinance
>>> from pprint import pprint
>>>
>>> x = yfinance.Ticker('HTOO')
>>> pprint(x)
yfinance.Ticker object <HTOO>
>>> pprint(x.info)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/virtualenv3/yfinance-env/lib/python3.8/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/data/virtualenv3/yfinance-env/lib/python3.8/site-packages/yfinance/base.py", line 446, in get_info
    self._get_fundamentals(proxy=proxy)
  File "/data/virtualenv3/yfinance-env/lib/python3.8/site-packages/yfinance/base.py", line 387, in _get_fundamentals
    key[0]['yearly'] = cleanup(data[item][key[2]])
  File "/data/virtualenv3/yfinance-env/lib/python3.8/site-packages/yfinance/base.py", line 253, in cleanup
    df = _pd.DataFrame(data).drop(columns=['maxAge'])
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
    return super().drop(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 3887, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 3921, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5284, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['maxAge'] not found in axis"
>>>
```

**Comment by kucharskim** [comment]
Was this fixed?

**Comment by ValueRaider** [comment]
Works for me
