### ISSUE TITLE
'regularMarketPrice' info is wrong

### ISSUE THREAD

**Issue by imoreapps** [ranaroussi/yfinance#604]
Why re-assign 'regularMarketPrice' with 'regularMarketOpen'?

`self._info['regularMarketPrice'] = self._info['regularMarketOpen']`

**Comment by danielcn** [comment]
I have the similar issue as mentioned above but for regularMarketOpen key:

```
>>> msft = yf.Ticker("itsa4")
>>> msft.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dnascimento/.local/share/virtualenvs/project-tL9ezB_y/lib/python3.8/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/Users/dnascimento/.local/share/virtualenvs/project-tL9ezB_y/lib/python3.8/site-packages/yfinance/base.py", line 446, in get_info
    self._get_fundamentals(proxy)
  File "/Users/dnascimento/.local/share/virtualenvs/project-tL9ezB_y/lib/python3.8/site-packages/yfinance/base.py", line 340, in _get_fundamentals
    **self._info['regularMarketPrice'] = self._info['regularMarketOpen']**
KeyError: 'regularMarketOpen'
```

**Comment by richardmillson** [comment]
@danielcn "itsa4" is not a valid ticker symbol, check out https://finance.yahoo.com/lookup?s=ITSA4 to see there are no results.

You are getting that KeyError because yfinance is trying to load info that doesn't exist, in this case the 'regularMarketOpen' value. It would be nice if the library had a specific error for invalid symbols.
