### ISSUE TITLE
Tickers calls won't get history for some indices

### ISSUE THREAD

**Issue by jtl125** [ranaroussi/yfinance#622]
I was trying to use the Tickers class to get the history for some Spanish indices (SAN.MC and BKT.MC) but the method raises the following error: 

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/path/to/project/venv/lib/python3.8/site-packages/yfinance/tickers.py", line 64, in history
    return self.download(
  File "/path/to/project/venv/lib/python3.8/site-packages/yfinance/tickers.py", line 91, in download
    getattr(self.tickers, symbol)._history = data[symbol]
AttributeError: 'Tickers' object has no attribute 'SAN.MC'
```

Using a Ticker class for each index or using the download function seems to work well. 

EDIT: Messed up and copied the wrong error message

**Comment by aglove2189** [comment]
This is happening with 'dashed' tickers as well like "BRK-B", link to issue: #641
