### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by SelcouthTech** [ranaroussi/yfinance#691]
While using library to download multiple tickers, I received the following traceback using this:

```
stock_history_data = yf.download(
        tickers = symbol_list,
        period = 'max',
        interval = '1d',
        group_by = 'ticker',
        actions = True,
        auto_adjust = False
 )
```

```
Exception in thread Thread-586:
Traceback (most recent call last):
  File "/home/market_data_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/market_data_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/market_data_env/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/market_data_env/lib/python3.7/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/home/market_data_env/lib/python3.7/site-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/home/market_data_env/lib/python3.7/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/home/market_data_env/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/market_data_env/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/market_data_env/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/market_data_env/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

To fix, I added ```Threads=False``` which seemed to allow the script to proceed as normal. Unsure if this is related to recent pull request by @jrdi or if it's a separate problem. Here's a solution for those that run into same problem.

**Comment by pipreaper** [comment]
I have an associated error after looping through several thousand iterations of accessing various tickers from various exchanges. I think the code in decode.py is not able to recover from a connection failure any work around or solution would be of course helpful.
![decoder py error](https://user-images.githubusercontent.com/48084410/115812399-395c7480-a3e9-11eb-8112-d45291718040.png)

**Comment by pipreaper** [comment]
So I inserted recommendations of @jrdi, above, Threads=False, ` data = pdr.get_data_yahoo(_ticker,  threads=False, start=_start_date, end=_end_date)
`
 Upgraded to yfinance-0.1.59.dist-info.

So far all seems to be good in my world.

Many Thanks

**Comment by impredicative** [comment]
`threads=False` seems to help. I also have `time.sleep(0.1)` after each read. I then got the this **fake** error as documented in #572:

```
RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***
Our engineers are working quickly to resolve the issue. Thank you for your patience.
```

**Comment by mingwugmail** [comment]
This problem may related to the Yahoo server side, I think we should improve the error condition checking & reporting to distinguish  whether it is client side error, or Yahoo server side, e.g. print out the *raw* json string on error.

**Comment by mingwugmail** [comment]
this worked for me:

https://github.com/ranaroussi/yfinance/issues/760#issuecomment-877355832

**Comment by JiaxinLIU0998** [comment]
> this worked for me:
> 
> [#760 (comment)](https://github.com/ranaroussi/yfinance/issues/760#issuecomment-877355832)

hi, I am new to Python, could you please talk about how you fix the issue in more detail? Thanks!
