### ISSUE TITLE
Issue in downloading stock market data using yfinance

### ISSUE THREAD

**Issue by SougataNandi** [ranaroussi/yfinance#708]
Hi All - I'm using the below code to pull the daily OHLCV data, but encountered the following ERROR. Any idea about the issue?

CODE:
stocks = ["TVSMOTOR.BO","SUNPHARMA.BO","KOTAKBANK.BO","RELIANCE.BO"]
year = 1
import datetime as dt
import yfinance as yf
import pandas as pd
start = dt.datetime.today()-dt.timedelta(365*year)
end = dt.datetime.today()
ohlcv_data = {}
for ticker in stocks:
    print("Downloading for "+ticker)
    ohlcv_data[ticker] = yf.download(ticker,start,end)

ERROR:
Downloading for TVSMOTOR.BO
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000016C0983C250>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sougata\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\Sougata\anaconda3\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/TVSMOTOR.BO?period1=1589025263&period2=1620561263&interval=1d&includePrePost=False&events=div%2Csplits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016C0983C250>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sougata\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Sougata\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\yfinance\multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\Sougata\anaconda3\lib\site-packages\yfinance\multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\Sougata\anaconda3\lib\site-packages\yfinance\base.py", line 151, in history
    data = _requests.get(url=url, params=params, proxies=proxy)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Sougata\anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/TVSMOTOR.BO?period1=1589025263&period2=1620561263&interval=1d&includePrePost=False&events=div%2Csplits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016C0983C250>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Traceback (most recent call last):

  File "<ipython-input-5-d82709c1e031>", line 10, in <module>
    ohlcv_data[ticker] = yf.download(ticker,start,end)

**Comment by Joseph-Adamik** [comment]
I am having the same issue.  yf.Ticker() works, but not yf.download.  What's this about limiting the request rate with sleep?

**Comment by tombohub** [comment]
If you are downloading lot of stocks in the loop then at the end of each loop put `time.sleep(seconds)` so the loop stops a little bit before downloading next stock
