### ISSUE TITLE
KeyError Timestamps

### ISSUE THREAD

**Issue by mbzand** [ranaroussi/yfinance#71]
For some lists of Tickers I get a KeyError on Timestamps. I guess it is caused by Tickers that do not have historical data. However, I don't know which tickers or a way to work around this. 
Do you have any suggestions?
This is the code:

```
df = yf.download(corr_assets[0:100], period="max", treads = True)
[*********************100%***********************]  100 of 100 downloaded
Traceback (most recent call last):
  File "C:\Users\Mbzan\Python\lib\site-packages\yfinance\__init__.py", line 541, in download
    data = _pd.concat(_DFS.values(), axis=1, keys=_DFS.keys())
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\reshape\concat.py", line 229, in concat
    return op.get_result()
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\reshape\concat.py", line 426, in get_result
    copy=self.copy)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\internals\managers.py", line 2065, in concatenate_block_managers
    return BlockManager(blocks, axes)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\internals\managers.py", line 114, in __init__
    self._verify_integrity()
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\internals\managers.py", line 311, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\internals\managers.py", line 1691, in construction_error
    passed, implied))
ValueError: Shape of passed values is (9293, 600), indices imply (9291, 600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mbzan\Python\lib\site-packages\yfinance\__init__.py", line 615, in _realign_dfs
    index=idx, data=_DFS[key]).drop_duplicates()
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\frame.py", line 390, in __init__
    dtype=dtype, copy=copy)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\generic.py", line 150, in _init_mgr
    copy=False)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\internals\managers.py", line 1196, in reindex_axis
    fill_value=fill_value, copy=copy)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\internals\managers.py", line 1224, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexes\base.py", line 3087, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mbzan\Python\lib\site-packages\yfinance\__init__.py", line 543, in download
    _realign_dfs()
  File "C:\Users\Mbzan\Python\lib\site-packages\yfinance\__init__.py", line 619, in _realign_dfs
    _DFS[key].loc[df.index, :] = df.values
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexing.py", line 189, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexing.py", line 167, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexing.py", line 248, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "C:\Users\Mbzan\Python\lib\site-packages\pandas\core\indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "[Timestamp('2004-05-31 00:00:00'), Timestamp('2019-05-27 00:00:00'), Timestamp('2004-01-19 00:00:00'), Timestamp('1995-05-29 00:00:00'), Timestamp('2007-07-04 00:00:00'), Timestamp('1998-02-16 00:00:00'), Timestamp('2003-02-17 00:00:00'), Timestamp('1997-11-27 00:00:00'), Timestamp('2010-11-25 00:00:00'), Timestamp('2000-02-21 00:00:00'), Timestamp('2004-11-25 00:00:00'), Timestamp('2019-01-21 00:00:00'), Timestamp('2018-11-22 00:00:00'), Timestamp('2001-09-13 00:00:00'), Timestamp('2006-01-16 00:00:00'), Timestamp('2006-02-20 00:00:00'), Timestamp('2009-11-26 00:00:00'), Timestamp('2004-02-16 00:00:00'), Timestamp('2018-12-05 00:00:00'), Timestamp('1999-01-18 00:00:00'), Timestamp('2004-06-11 00:00:00'), Timestamp('2012-07-04 00:00:00'), Timestamp('1998-07-03 00:00:00'), Timestamp('2008-01-21 00:00:00'), Timestamp('2005-05-30 00:00:00'), Timestamp('2007-01-02 00:00:00'), Timestamp('2015-01-19 00:00:00'), Timestamp('2007-01-15 00:00:00'), Timestamp('1995-02-20 00:00:00'), Timestamp('2001-01-15 00:00:00'), Timestamp('2011-01-17 00:00:00'), Timestamp('2001-05-28 00:00:00'), Timestamp('2009-05-25 00:00:00'), Timestamp('1997-02-17 00:00:00'), Timestamp('2002-01-21 00:00:00'), Timestamp('2005-01-17 00:00:00'), Timestamp('2005-07-04 00:00:00'), Timestamp('2013-07-04 00:00:00'), Timestamp('2001-09-14 00:00:00'), Timestamp('1997-05-26 00:00:00'), Timestamp('2006-11-23 00:00:00'), Timestamp('2018-01-15 00:00:00'), Timestamp('2015-11-26 00:00:00'), Timestamp('2006-07-04 00:00:00'), Timestamp('2012-11-22 00:00:00'), Timestamp('1996-07-04 00:00:00'), Timestamp('1996-11-28 00:00:00'), Timestamp('2017-01-16 00:00:00'), Timestamp('1997-07-04 00:00:00'), Timestamp('2014-01-20 00:00:00'), Timestamp('2010-01-18 00:00:00'), Timestamp('2002-07-04 00:00:00'), Timestamp('2002-05-27 00:00:00'), Timestamp('2008-11-27 00:00:00'), Timestamp('1999-12-24 00:00:00'), Timestamp('2012-10-30 00:00:00'), Timestamp('2003-11-27 00:00:00'), Timestamp('2001-02-19 00:00:00'), Timestamp('2013-11-28 00:00:00'), Timestamp('1995-07-04 00:00:00'), Timestamp('2012-05-28 00:00:00'), Timestamp('2000-07-04 00:00:00'), Timestamp('2017-11-23 00:00:00'), Timestamp('2002-02-18 00:00:00'), Timestamp('2007-02-19 00:00:00'), Timestamp('2011-11-24 00:00:00'), Timestamp('2000-05-29 00:00:00'), Timestamp('2002-11-28 00:00:00'), Timestamp('1999-11-25 00:00:00'), Timestamp('2006-05-29 00:00:00'), Timestamp('2014-11-27 00:00:00'), Timestamp('1998-05-25 00:00:00'), Timestamp('2001-11-22 00:00:00'), Timestamp('2008-05-26 00:00:00'), Timestamp('2004-12-24 00:00:00'), Timestamp('2003-05-26 00:00:00'), Timestamp('1999-02-15 00:00:00'), Timestamp('2016-11-24 00:00:00'), Timestamp('2011-05-30 00:00:00'), Timestamp('2007-11-22 00:00:00'), Timestamp('1995-11-23 00:00:00'), Timestamp('2007-05-28 00:00:00'), Timestamp('2012-10-29 00:00:00'), Timestamp('1998-01-19 00:00:00'), Timestamp('2018-07-04 00:00:00'), Timestamp('2010-07-05 00:00:00'), Timestamp('2014-05-26 00:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('1999-05-31 00:00:00'), Timestamp('2003-07-04 00:00:00'), Timestamp('2016-07-04 00:00:00'), Timestamp('2005-02-21 00:00:00'), Timestamp('2017-07-04 00:00:00'), Timestamp('1999-07-05 00:00:00'), Timestamp('2011-07-04 00:00:00'), Timestamp('2014-07-04 00:00:00'), Timestamp('2016-05-30 00:00:00'), Timestamp('1996-05-27 00:00:00'), Timestamp('2015-05-25 00:00:00'), Timestamp('2009-07-03 00:00:00'), Timestamp('2013-01-21 00:00:00'), Timestamp('2010-05-31 00:00:00'), Timestamp('2017-05-29 00:00:00'), Timestamp('2018-05-28 00:00:00'), Timestamp('2005-11-24 00:00:00'), Timestamp('2000-11-23 00:00:00'), Timestamp('1996-02-19 00:00:00'), Timestamp('2008-07-04 00:00:00'), Timestamp('2015-07-03 00:00:00'), Timestamp('2004-07-05 00:00:00'), Timestamp('2000-01-17 00:00:00'), Timestamp('2013-05-27 00:00:00'), Timestamp('2010-12-24 00:00:00'), Timestamp('1998-11-26 00:00:00'), Timestamp('2001-07-04 00:00:00'), Timestamp('2003-01-20 00:00:00'), Timestamp('2012-01-16 00:00:00'), Timestamp('2009-01-19 00:00:00')] not in index"
```

**Comment by ranaroussi** [comment]
Are you using version 0.1.40+? This type of error should have been resolved. Can you please upgrade and confirm if that error is gone or still exist?

```
$ pip install yfinance --upgrade --no-cache-dir
```

Thanks!

**Comment by mbzand** [comment]
I am using version 0.1.41: 
Requirement already up-to-date: yfinance in c:\users\mbzan\python\lib\site-packages (0.1.41)

But the error is still persisting for some tickers, not all though.

**Comment by mbzand** [comment]
> Are you using version 0.1.40+? This type of error should have been resolved. Can you please upgrade and confirm if that error is gone or still exist?
> 
> ```
> $ pip install yfinance --upgrade --no-cache-dir
> ```
> 
> Thanks!

I am using version 0.1.41:
Requirement already up-to-date: yfinance in c:\users\mbzan\python\lib\site-packages (0.1.41)

But the error is still persisting for some tickers, not all though.

**Comment by ranaroussi** [comment]
Can you post here the 100 tickers you're trying to download? I want to try and replicate this error on my machine so I can dig into it.

**Comment by mbzand** [comment]
> Can you post here the 100 tickers you're trying to download? I want to try and replicate this error on my machine so I can dig into it.

I found that it must be one of the last 50 tickers since the first 50 won't give this error. The last 50 tickers are: 
```
corr_assets[50:100]
['ELUX-B.ST', 'BAM-PFI.TO', 'BAM-PFA.TO', 'ENL.DE', 'BAM-PFG.TO', 'DAI.SW', 'BCE-PF.TO', 'BCE-PC.TO', 'LUN.CO', 'BCE-PA.TO', 'BCE-PD.TO', 'BCE-PB.TO', 'BCE-PY.TO', 'BCE-PH.TO', 'BCE-PG.TO', 'DAN.SW', 'SCA-A.ST', 'CAST.ST', 'ZURN.SW', 'FABG.ST', 'LLD.DE', 'MFC-PO.TO', 'MFC-PR.TO', 'SALM.OL', 'TD-PFA.TO', 'TD-PFC.TO', 'INN1.DE', 'TNE5.DE', 'HUFV-A.ST', 'TREL-B.ST', 'FMC1.DE', 'BOY.DE', 'ISP.MI', 'IES.DE', 'HOLM-B.ST', 'MUV2.DE', 'WALL-B.ST', 'INTRUM.ST', 'GWO-PN.TO', 'GWO.TO', 'IMO.TO', 'PNDX-B.ST', 'SRBANK.OL', 'SCMN.SW', 'AENA.MC', 'PNDORA.CO', 'CON.DE', 'ENTRA.OL', 'HPOL-B.ST', 'LOOM-B.ST']
```

**Comment by mbzand** [comment]
Also, I want to add something: if I download this last 50 in one try (thus: `df = yf.download(corr_assets[50:100], period="max", treads = True)`) it will give the error. 

However, if I download them in batches of 10, there is no error. So this works:
```
df = yf.download(corr_assets[50:60], period="max", treads = True)
df = yf.download(corr_assets[60:70], period="max", treads = True)
df = yf.download(corr_assets[70:80], period="max", treads = True)
df = yf.download(corr_assets[80:90], period="max", treads = True)
df = yf.download(corr_assets[90:100], period="max", treads = True)
```

**Comment by stanlee1986** [comment]
I've replicated this. The issue is days with stock splits and/or dividends but no prices. Dropping TD-PFA.TO, HOLM-B.ST, IMO.TO eliminates the problem. Alternately running` .dropna(`) on `yf.Ticker(ticker).history(start="2017-01-01", auto_adjust=True)` drops the offending entries but keeps the rest. Not sure how best to actually deal with this, especially for auto_adjust. auto_adjust doesn't affect the results.


```
tickers = ['ELUX-B.ST', 'BAM-PFI.TO', 'BAM-PFA.TO', 'ENL.DE', 'BAM-PFG.TO', 'DAI.SW', 'BCE-PF.TO', 'BCE-PC.TO', 'LUN.CO', 'BCE-PA.TO', 'BCE-PD.TO', 'BCE-PB.TO', 'BCE-PY.TO', 'BCE-PH.TO', 'BCE-PG.TO', 'DAN.SW', 'SCA-A.ST', 'CAST.ST', 'ZURN.SW', 'FABG.ST', 'LLD.DE', 'MFC-PO.TO', 'MFC-PR.TO', 'SALM.OL', 'TD-PFA.TO', 'TD-PFC.TO', 'INN1.DE', 'TNE5.DE', 'HUFV-A.ST', 'TREL-B.ST', 'FMC1.DE', 'BOY.DE', 'ISP.MI', 'IES.DE', 'HOLM-B.ST', 'MUV2.DE', 'WALL-B.ST', 'INTRUM.ST', 'GWO-PN.TO', 'GWO.TO', 'IMO.TO', 'PNDX-B.ST', 'SRBANK.OL', 'SCMN.SW', 'AENA.MC', 'PNDORA.CO', 'CON.DE', 'ENTRA.OL', 'HPOL-B.ST', 'LOOM-B.ST']
_DFS = {}

for ticker in tickers:
  temp = yf.Ticker(ticker).history(start="2017-01-01", auto_adjust=True)
  errors = temp.loc[np.any(temp.isnull(), axis=1)]
  if len(errors) > 0:
    print(ticker, errors)
  _DFS[ticker.upper()] = temp

#df = pd.concat(_DFS.values(), axis=1, keys=_DFS.keys())
```

`TD-PFA.TO             Open  High  Low  Close  Volume  Dividends  Stock Splits
Date                                                               
2018-07-09   NaN   NaN  NaN    NaN     NaN    0.24375             0
HOLM-B.ST             Open  High  Low  Close  Volume  Dividends  Stock Splits
Date                                                               
2018-04-30   NaN   NaN  NaN    NaN     NaN        0.0           2.0
IMO.TO             Open  High  Low  Close  Volume  Dividends  Stock Splits
Date                                                               
2019-05-31   NaN   NaN  NaN    NaN     NaN       0.22             0`

**Comment by ranaroussi** [comment]
Please upgrade to the latest version and let me know if this error is gone

**Comment by mbzand** [comment]
Hi Ran, 
It works perfectly! I tested it on around 2000 tickers without an error. 
Thank you for your work, it makes life much easier (I implemented 3 of your packages in my code now)

**Comment by ranaroussi** [comment]
Glad to hear it! ...and thanks :)
