### ISSUE TITLE
AttributeError: partially initialized module 'pandas_datareader.data' has no attribute 'get_data_yahoo' (most likely due to a circular import)

### ISSUE THREAD

**Issue by msrajanadar** [ranaroussi/yfinance#741]
```python
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")

Error:
Traceback (most recent call last):
  File "/Users/vnadar/Documents/Projects/python/YahooFin/pandas.py", line 1, in <module>
    from pandas_datareader import data as pdr
  File "/Users/vnadar/Documents/Projects/python/YahooFin/venv/lib/python3.9/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (
  File "/Users/vnadar/Documents/Projects/python/YahooFin/venv/lib/python3.9/site-packages/pandas_datareader/data.py", line 9, in <module>
    from pandas.util._decorators import deprecate_kwarg
  File "/Users/vnadar/Documents/Projects/python/YahooFin/pandas.py", line 7, in <module>
    data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")
AttributeError: partially initialized module 'pandas_datareader.data' has no attribute 'get_data_yahoo' (most likely due to a circular import)

Process finished with exit code 1

**Comment by chuckf201** [comment]
I, too am having the same issue. I'm using anaconda 2.0.3 and spyder 5.0.3
AttributeError: partially initialized module 'yfinance' has no attribute 'Ticker' (most likely due to a circular import)
