### ISSUE TITLE
404 when retrieving info of a given ticker

### ISSUE THREAD

**Issue by JMKwins** [ranaroussi/yfinance#756]
Have you also this error ? 
This is quite impacting. .info gives 404 errors. Any idea on how to correct this ? 
 ```python
>>> import yfinance as yf
>>> 
>>> msft = yf.Ticker("MSFT")
>>> 
>>> # get stock info
```
```bash
... msft.info
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "yfinance/base.py", line 426, in get_info
    self._get_fundamentals(proxy)
  File "yfinance/base.py", line 284, in _get_fundamentals
    holders = _pd.read_html(url)
...
    with closing(_urlopen(*args, **kwargs)) as f:
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by nunnsy** [comment]
Make sure you update your package to 0.1.60

**Comment by silvavn** [comment]
Solved in latest release, please update.
