### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by draew6** [ranaroussi/yfinance#760]
Hi, I am using yfinance daily. Thank you very much for support! But today I received on all scripts I am using this error:
Something changed with new version that is causing this?

Traceback (most recent call last):
  File "C:/Users/user/Desktop/NOTES/Codes/project/yf.py", line 7, in <module>
    prices.append(yf.Ticker(ticker).history(period="1d")["Close"].values[0])
  File "C:\Users\user\Desktop\NOTES\Codes\projectI\venv\lib\site-packages\yfinance\base.py", line 157, in history
    data = data.json()
  File "C:\Users\user\Desktop\NOTES\Codes\project\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PatrickDionne** [comment]
Getting same issue now on the yf.download() call, but used it successfully this morning. Didn't make any changes to my version today.

**Comment by dennistamyf** [comment]
Is experiencing the same problem. Was running my service normally as of last night.

**Comment by GuyHersh** [comment]
Also same issue, was working fine in the past about an hour ago.  I was on an older version of yfinance, same error before and after updating.

**Comment by hshi0001** [comment]
Same here, worked well 2 hours ago

**Comment by daneasterman** [comment]
Yep same error for me as well when running any of the history commands, for example: `msft.history(period="max")`
I'm on this version: `yfinance==0.1.59`
Thanks for your help in advance!

**Comment by ywluohao** [comment]
same issue, is yahoo finance updating again...sigh

**Comment by rubikscube09** [comment]
Same issue :(

**Comment by chandakrishabh** [comment]
Also having the same issue!

**Comment by shivpalit** [comment]
me too! Getting this error though. With 0.1.59 and 0.1.61

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/shivpalit/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/shivpalit/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 170, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 185, in _download_one
    rounding=rounding, many=True)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/yfinance/base.py", line 157, in history
    data = data.json()
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/shivpalit/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mingwugmail** [comment]
dup:

https://github.com/ranaroussi/yfinance/issues/363
https://github.com/ranaroussi/yfinance/issues/691

looks like it's Yahoo server side problem.

**Comment by torolearning101** [comment]
same same.... can't believe they can't make it more stable.

**Comment by hshi0001** [comment]
happened before?

**Comment by Quantaria** [comment]
Same issue this morning. Happened mid-day.

**Comment by ForeverZyh** [comment]
https://github.com/ranaroussi/yfinance/blob/1cc8d969f9b9966ea4c905f9dcab52ffd7cd8d31/yfinance/base.py#L157

`data` in this line returns something like `b'Forbidden'`. Agree with @mingwugmail, seems like Yahoo side problem.

**Comment by djl0** [comment]
for me, adding a user agent fixed the problem:
```headers = {'User-Agent': 'Firefox'}
data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)```
https://github.com/ranaroussi/yfinance/blob/1cc8d969f9b9966ea4c905f9dcab52ffd7cd8d31/yfinance/base.py#L152

But I'm not sure what the user-agent should be for a project like this, so I'm hesitant to create a PR for this.

**Comment by y11z** [comment]
> for me, adding a user agent fixed the problem:
> 
> `headers = {'User-Agent': 'Firefox'}`
> `data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)`

I tried

**Comment by y11z** [comment]
> for me, adding a user agent fixed the problem:
> 
> `headers = {'User-Agent': 'Firefox'}`
> `data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)`
> 
I tried, no luck, PC, python. Window 10.

Exception in thread Thread-25:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\base.py", line 154, in history
    data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)
AttributeError: 'Ticker' object has no attribute 'session'

**Comment by xy345** [comment]
> for me, adding a user agent fixed the problem:
> 
> `headers = {'User-Agent': 'Firefox'}`
> `data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)`
> 
> https://github.com/ranaroussi/yfinance/blob/1cc8d969f9b9966ea4c905f9dcab52ffd7cd8d31/yfinance/base.py#L152
> 
> But I'm not sure what the user-agent should be for a project like this, so I'm hesitant to create a PR for this.

Worked for me.

**Comment by mingwugmail** [comment]
@y11z 

can you also try add `threads=False`:

```
df = pdr.get_data_yahoo(symbol, start=start_date, progress=False, threads=False)
```

**Comment by mingwugmail** [comment]
> for me, adding a user agent fixed the problem:
> 
> `headers = {'User-Agent': 'Firefox'}`
> `data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)`
> 
> https://github.com/ranaroussi/yfinance/blob/1cc8d969f9b9966ea4c905f9dcab52ffd7cd8d31/yfinance/base.py#L152
> 
> But I'm not sure what the user-agent should be for a project like this, so I'm hesitant to create a PR for this.

It worked for me as well, on Linux.

@djl0  I think you definitely should create a PR.

**Comment by rubikscube09** [comment]
> > for me, adding a user agent fixed the problem:
> > `headers = {'User-Agent': 'Firefox'}`
> > `data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)`
> > https://github.com/ranaroussi/yfinance/blob/1cc8d969f9b9966ea4c905f9dcab52ffd7cd8d31/yfinance/base.py#L152
> > 
> > But I'm not sure what the user-agent should be for a project like this, so I'm hesitant to create a PR for this.
> 
> Worked for me.


What's the best way to edit the package and implement these changes locally? Would like to try it myself.

**Comment by y11z** [comment]
> @y11z
> 
> can you also try add `threads=False`:
> 
> ```
> df = pdr.get_data_yahoo(symbol, start=start_date, progress=False, threads=False)
> ```

thanks, but still no luck

yf.download('SPY', '2018-10-26', '2021-07-09',progress=False, threads=False)

=====
  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\multi.py", line 100, in download
    data = _download_one(ticker, period=period, interval=interval,

  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,

  File "C:\ProgramData\Anaconda3\lib\site-packages\yfinance\base.py", line 153, in history
    data = self.session.get(url=url, headers=headers, params=params, proxies=proxy)

AttributeError: 'Ticker' object has no attribute 'session'

**Comment by ranaroussi** [comment]
Fixed with 0.1.62.

Please upgrade using `pip install -U yfinance`

**Comment by lfelipecid** [comment]
> headers = {'User-Agent': 'Firefox'}

Worked for me!

**Comment by JiaxinLIU0998** [comment]
The same issue 

> Fixed with 0.1.62.
> 
> Please upgrade using `pip install -U yfinance`

It seems that upgrading does not work for me

**Comment by ranaroussi** [comment]
@JiaxinLIU0998 try:
```pip install yfinance -U--no-cache-dir```

**Comment by goldmonkey21** [comment]
Fixed it by installing from git:

pip uninstall yfinance
pip install git+https://github.com/ranaroussi/yfinance.git#egg=yfinance

Works!

**Comment by shivpalit** [comment]
Anyone know how to fix this issue on Heroku? What should be added to the requirements file?

**Comment by ranaroussi** [comment]
See issue #764

**Comment by jalfgit** [comment]
i noticed the fix with the upgrade. anyone seeing adj close column coming through?

**Comment by NabanCodes** [comment]
pip install -U yfinance worked for me
