### ISSUE TITLE
Thread Exception on download()

### ISSUE THREAD

**Issue by joecaraccio** [ranaroussi/yfinance#769]
Just trying to query some simple data for Eth, I get a thread exception. At first I just assumed maybe the API of yfinance was down and went to bed (as it was working all day yesterday), but now this continues to happen. I haven't stepped into the library to debug what is going on, but did something deprecate? did my IP somehow get banned (I don't think this was the case)...anyone experiencing anything similar?

```
start = dt.datetime(2020,1,1)
end = dt.datetime.now()
eth = yfinance.download('ETH', start, end)
```

I get an exception:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    data = data.json()
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jacar\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\jacar\Documents\SportDB\misc\market\stargate\stargate.py", line 29, in <module>
    eth = yfinance.download('ETH', start, end)

**Comment by nickion** [comment]
Getting the same with the latest 0.1.62

**Comment by ranaroussi** [comment]
Please
