### ISSUE TITLE
Can yfinance deal with anti-scrapping features of yahoo finance?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [ranaroussi/yfinance#770]
```
>>> import requests
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import http.client
>>> http.client.HTTPConnection.debuglevel=1
>>> import yfinance as yf
>>> ticker = yf.Ticker('MSFT')
>>> data = ticker.history(period='max')
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query1.finance.yahoo.com:443
send: b'GET /v8/finance/chart/MSFT?period1=-2208988800&period2=1625921757&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1\r\nHost: query1.finance.yahoo.com\r\nUser-Agent: python-requests/2.25.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Date: Sat, 10 Jul 2021 12:55:58 GMT
header: Strict-Transport-Security: max-age=15552000
header: Server: ATS
header: Cache-Control: no-store
header: Content-Type: text/html
header: Content-Language: en
header: Referrer-Policy: no-referrer-when-downgrade
header: X-Frame-Options: SAMEORIGIN
header: Content-Length: 9
header: Age: 0
header: Connection: keep-alive
header: Expect-CT: max-age=31536000, report-uri="http://csp.yahoo.com/beacon/csp?src=yahoocom-expect-ct-report-only"
header: X-XSS-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
DEBUG:urllib3.connectionpool:https://query1.finance.yahoo.com:443 "GET /v8/finance/chart/MSFT?period1=-2208988800&period2=1625921757&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1" 403 9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yfinance/base.py", line 157, in history
    data = data.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I got the above error. But the URL is accessible in a browser. Does it mean that yfinance cannot deal with anti-scrapping features of yahoo finance? If so, can this feature be added?

https://query1.finance.yahoo.com/v8/finance/chart/MSFT?period1=-2208988800&period2=1625921757&interval=1d&includePrePost=False&events=div%2Csplits

**Comment by ranaroussi** [comment]
Please see #764

**Comment by prRZ5F4LXZ** [comment]
In the new version output, I see the user agent is changed to Mozilla... Is this the bug fix? Or the bug fix is in some other place?

```
send: b'GET /v8/finance/chart/MSFT?period1=-2208988800&period2=1625974837&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1\r\nHost: query2.finance.yahoo.com\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
```
