### ISSUE TITLE
SSL Issue while using HTTP/HTTPS Proxy

### ISSUE THREAD

**Issue by pranjal-joshi** [ranaroussi/yfinance#781]
After upgrading to **v0.1.63**, I am getting **SSL-related issues** while using the PC through HTTP/S Proxy.

The same program works over another computer without a network proxy.

Earlier, `proxyServer = urllib.request.getproxies()['http']` were working fine with
```
data = yf.download(
                tickers=stockCode+".NS",
                period=period,
                duration=duration,
                proxy=proxyServer,
                progress=False,
            )
```

Here's a traceback log!

```
Exception in thread Thread-1:       
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 950, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 662, in urlopen
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
Exception in thread Thread-1:
Traceback (most recent call last):
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 662, in urlopen
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 950, in _prepare_proxy
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 950, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
    return context.wrap_socket(sock, server_hostname=server_hostname)
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    return self.sslsocket_class._create(
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    self._sslobj.do_handshake()
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/NESTLEIND.NS?range=300d&interval=1d&includePrePost=False&events=div%2Csplits (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

```

**Comment by pranjal-joshi** [comment]
Hello,
This issue is still **not resolved!**
Can anyone provide a solution?

**Comment by GitHubDiom** [comment]
@pranjal-joshi 
I also have this issue, and the function I used in my project is `yf.history()`

I temporarily solved this issue by modifying the source code and run `pip install -e .`.

In `yfinance/base.py`, the request of the `history` function is sent in line 152 ` data = self.session.get(XXX)`.

Then I add a param `verify= verify ` to determine the certification of SSL.

At the function declaration (Line 77 in `yfinance/base.py`), add a default param `verify`, and set it as `True` as default.

After the above done, run `pip install -e .` in the root directory of the yfiance project.
```bash
$ cd yfinance
$ pip install -e .
```

Then you can bypass the SSL verify by `yf.history(XXXX, verify=False)`

Note that it is just a temporary solution!
