### ISSUE TITLE
Some Tickers (FOREX) Giving JSON Errors - Version 0.1.63

### ISSUE THREAD

**Issue by JStyborski** [ranaroussi/yfinance#792]
After upgrading to escape some of the JSON errors mentioned in previous bug reports, some tickers still give JSON errors. All stocks/ETFs that I tested worked without issue. However any FOREX tickers (e.g., "EUR/USD", "USD/JPY") give the same JSON error that I was receiving previously before the upgrade to 0.1.63.

I only tried FOREX tickers recently, so perhaps they always gave this error?

Sample output below, with successful AAPL run for comparison:

yf.Ticker('AAPL').history(period='1y', interval='1d').head()
Out[33]: 
                 Open       High        Low  ...     Volume  Dividends  Stock Splits
Date                                         ...                                    
2020-07-22  96.045332  97.319250  95.955938  ...   89001600        0.0           0.0
2020-07-23  96.348291  96.427757  91.394177  ...  197004400        0.0           0.0
2020-07-24  90.378523  92.347752  88.548348  ...  185438800        0.0           0.0
2020-07-27  93.082794  94.269796  92.854338  ...  121214000        0.0           0.0
2020-07-28  93.735900  93.917181  92.623393  ...  103625600        0.0           0.0

[5 rows x 7 columns]

type(yf.Ticker('EUR/USD'))
Out[34]: yfinance.ticker.Ticker

yf.Ticker('EUR/USD').history(period='1y', interval='1d')
Traceback (most recent call last):

  File "<ipython-input-35-c89633175491>", line 1, in <module>
    yf.Ticker('EUR/USD').history(period='1y', interval='1d')

  File "C:\Users\jerem\anaconda3\lib\site-packages\yfinance\base.py", line 162, in history
    data = data.json()

  File "C:\Users\jerem\anaconda3\lib\site-packages\requests\models.py", line 889, in json
    return complexjson.loads(

  File "C:\Users\jerem\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)

  File "C:\Users\jerem\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\jerem\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by TaoTsing** [comment]
I get the same error. Even when I try for AAPL.
No matter what Ticker-symbol...

**Comment by TaoTsing** [comment]
Mine went away after updating through PIP:
pip3 install yfinance --upgrade --no-cache-dir

**Comment by icbroff** [comment]
same errors no matter what ticker.  updating didn't work either

**Comment by super6liu** [comment]
> same errors no matter what ticker. updating didn't work either

Adding `requests_cache` session cache worked for me.

**Comment by super6liu** [comment]
@ranaroussi , the trick is only passing in the `session` parameter when creating a `Ticker`. It was from your doc https://github.com/ranaroussi/yfinance#the-ticker-module.

```python
session = requests_cache.CachedSession('yfinance.cache')
session.headers['User-agent'] = 'project/1.0'
yf.Ticker('A', session)
```

My yfinance has always been on 0.1.59. But started to notice the JSONDecoratorError a few days ago. Just tested, I can repo now if not passing in a `session`.
