### ISSUE TITLE
Error when running yfinance-script on heroku?

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#832]
I have a python program which is running fine on my local machine with this statements:
```
    tday = datetime.today()
    startDay = tday - timedelta(days=2200)            
    print(f"Read stock price data for {stock}...")
    hist_price_stock = yf.download(stock,start=startDay,end=tday)
```
but when i deploy the code to heroku and try to run it here i get this json-error when calling the "yf.download..."

```
Read stock price data for AAPL...
Exception in thread Thread-1:
Traceback (most recent call last):
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/app/.heroku/python/lib/python3.9/site-packages/yfinance/multi.py", line 179, in _download_one
  File "/app/.heroku/python/lib/python3.9/site-packages/yfinance/base.py", line 157, in history
    data = data.json()
  File "/app/.heroku/python/lib/python3.9/site-packages/requests/models.py", line 900, in json
  File "/app/.heroku/python/lib/python3.9/json/__init__.py", line 346, in loads
  File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
^CTraceback (most recent call last):
  File "/app/LevermannBackend.py", line 72, in <module>
    erg = yc.calcLevermannScore(stock)
  File "/app/StockCrawler.py", line 3399, in calcLevermannScore
    hist_price_stock = yf.download(stock,start=startDay,end=tday)
  File "/app/.heroku/python/lib/python3.9/site-packages/yfinance/multi.py", line 95, in download
    _time.sleep(0.01)
```

Any ideas why this is not running on heroku in the cloud but fine on my local client?

I also tried to reinstall yfinance (and also pandas-datareader - cause i saw this in a stackoverflow-article) - but it doesn´t help anything:
```
pip uninstall yfinance
pip uninstall pandas-datareader
pip install yfinance --upgrade --no-cache-dir
pip install pandas-datareader
```

**Comment by qmpzaltb** [comment]
My guess is that Yahoo blacklisted or rate-limited the Heroku IPs since a lot of other people may have the same idea as you.

You could try setting up your own proxy and use the `proxy=...` [kwargs in the YF methods](https://github.com/ranaroussi/yfinance/blob/main/README.rst#the-ticker-module), but that'd defeat the purpose of using Heroku in the first place (i.e, if you're running a proxy on your computer, you may as well run the app there itself)

**Comment by Rapid1898-code** [comment]
I am not sure if this is the reason - cause in the program i am also scrapping data from yahoo finance additonal - and i have no problems with the heroku ip at all - only when i want to access with yfinance.

Is there anyway to try this with an nordvpn as a proxy using yfinance?
(have no working proxy by hand)

**Comment by qmpzaltb** [comment]
You're right. Based on the logs, it looks your Heroku app might be using an older version of `yfinance` - at least `0.1.59` or older (based on the fact that line 95 of `multi.py`  in your logs is actually found at line 97 now)

https://github.com/ranaroussi/yfinance/issues/764 says that you can fix this kind of error by upgrading to at least `0.1.62` (it's at `0.1.63` now)

**Comment by Rapid1898-code** [comment]
Ok i see - so i only have to use the updated version of yfinance in the requirements.txt for heroku and then everything should work fine - Thanks!
