### ISSUE TITLE
ValueError: Type names and field names must be valid identifiers: 'XXXX.YY'

### ISSUE THREAD

**Issue by raffieeey** [ranaroussi/yfinance#88]
When trying to use the `Tickers` class for symbol outside US that requires to put a dot. Error will come out e.g.

```
import yfinance as yf
tickers = yf.Tickers('MU7.SI D05.SI K6S.SI')

#Traceback (most recent call last):
#
#  File "<ipython-input-150-5977cf239722>", line 1, in <module>
#    tickers = yf.Tickers('MU7.SI D05.SI K6S.SI')
#
#  File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\yfinance\__init__.py", line 69, in #__init__
#    "Tickers", ticker_objects.keys())(*ticker_objects.values())
# 
#  File "..\AppData\Local\Continuum\anaconda3\lib\collections\__init__.py", line 361, in namedtuple
#    raise ValueError('Type names and field names must be valid '

##ValueError: Type names and field names must be valid identifiers: 'MU7.SI'
```

or 
```
import yfinance as yf
tickers = yf.Tickers('PTT.BK AOT.BK PTTEP.BK')

#Traceback (most recent call last):
#
#  File "<ipython-input-150-5977cf239722>", line 1, in <module>
#    tickers = yf.Tickers('PTT.BK AOT.BK PTTEP.BK')
#
#  File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\yfinance\__init__.py", line 69, in #__init__
#    "Tickers", ticker_objects.keys())(*ticker_objects.values())
#
#  File "..\AppData\Local\Continuum\anaconda3\lib\collections\__init__.py", line 361, in namedtuple
#    raise ValueError('Type names and field names must be valid '

##ValueError: Type names and field names must be valid identifiers: 'PTT.BK'
```

**Comment by ranaroussi** [comment]
Closing for now. Please reopen issue if the problem persists.
