### ISSUE TITLE
Exception in thread - JSONDecodeError - Not able to get tickers

### ISSUE THREAD

**Issue by turbo1618** [ranaroussi/yfinance#881]
I am still really new to learning python. I have been having problems getting data from yfinance. I can pull small amounts of data using some programs, but I'm not able to pull data using 200+ tickers. My programs have been working great for the last 3 months, but just in the last week, I have been having problems. It started when I wrote a new program that pulls data for 1938 tickers. I am using Jupyter.

```
tickers = ['IWM',
           'QQQ','SPY','DIA','MDY',
           'XLC','XLY','XLP','XLE','XLF','XLV','XLI','XLRE','XLB','XLK','XLU',
           'IWF','IVW','IWD','IVE','SPHB','IWC','IWV',
           'XBI','KBE','KRE','KCE','KIE','XHE','XHS','XHB','XWEB','VNQ','XOP','XES','XPH','XTL','XTN','XRT',
           'SOXX','IYT','IHE','SKYY','FDN','XSW','IYW','IHI','IYH','ITB','ITA','IYC','IHF','IYK','IAI','AIEQ',
           'IFRA','IHAK','TECB','IRBO','IDRV','IDNA','IXP','IEO','IGN','IEZ','IEIH','PBJ','PEJ','PBS','PXQ','PEZ','JETS',
           'GLD','GDX','GDXJ','JNUG','SLV','SIL','SILJ','PPLT','CPER','COPX','REMX','SLX','JJT','JJU','JJN','PALL','DBB',
           'LIT','USO','UNG','FCG','UGA','URA','URNM','JO','BAL','COW','WOOD','HAP','DBA','VEGI','PHO','GRN','KRBN',
           'CORN','WEAT','SOYB','CANE','MJ','MOO','NIB','LAND','COMT','XME','CRAK','NANR','PXE','BNO','FTXN',
           'ARKK','ARKQ','ARKW','ARKG','ARKF','PRNT',
           'BJK','NLR','ESPO','BOTZ','FINX','FTXO','CLOU','DRIV','SNSR','SOCL','EBIZ','AIQ','BFIT',
           'HAIL','ICLN','XT','TAN','IPO','FIVG','QTUM','VICE','COWZ','CALF','BATT','CIBR','ROBO','CARZ',
           'FFTY','BOUT','KARS','KWEB','CHIR','CHIC','TAIL','QCLN','IBUY','IPAY','ITEQ','BDRY',
           'PKB','DTEC','PAWZ','EMTY','CLIX','ONLN','SRVR','PAVE','PSP','KBWP','SPYX','BLCN','PSJ',
           'EEM','MCHI','EWW','ILF','EWZ','INDA','IEUR','EWY','RSX','EWJ','EWT','EWC','EWU','EWG','EWL','EWA','EWQ','EWP','EWS',
           'EWD','EWI','ECH','THD','EIDO','EWN','TUR','EPOL','EZA','EWM','EDEN','EIS','ENZL','EPHE','EWO','EMFM','CQQQ','EMQQ',
           'EWH','EIRL','ENOR','EFNL','EWK','EPU','ICOL','KSA','QAT','UAE',
           'UUP','FXE','FXF','FXY','FXC','FXB','FXA',
           'VXX','SVXY','UVXY','VIXM','VXZ','VIXY',
           'TLT','IEF','IEI','SHY','JNK','AGG','LQD','ANGL','PFF','TIP','LTPZ','RINF','MBB','MUB','GOVT',
           'GBTC','ETHE','BLOK',
           'SMH','EFA','MSOS','FXI',]

now = dt.datetime.now()
df = yf.download(tickers, '2019-01-01', now)['Adj Close']
df.fillna(method='ffill', inplace=True)
df
```

```
[********              16%                       ]  41 of 261 completed
Exception in thread Thread-49:
Traceback (most recent call last):
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 181, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\base.py", line 179, in history
    data = data.json()
  File "C:\Users\arswe\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[*************         28%                       ]  73 of 261 completed
Exception in thread Thread-82:
Traceback (most recent call last):
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 181, in _download_one
Exception in thread     return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\base.py", line 179, in history
Thread-84:
Traceback (most recent call last):
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
        self.run()
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 870, in run
data = data.json()
  File "C:\Users\arswe\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\json\__init__.py", line 357, in loads
[**************        29%                       ]  75 of 261 completed
    return _default_decoder.decode(s)
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 337, in decode
    return callee(*args, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 355, in raw_decode
data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 181, in _download_one
        raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\base.py", line 179, in history
    data = data.json()
  File "C:\Users\arswe\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[*******************   40%                       ]  105 of 261 completed
Exception in thread Thread-118:
Traceback (most recent call last):
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
[********************  41%                       ]  108 of 261 completed
    return callee(*args, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 181, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\base.py", line 179, in history
    data = data.json()
  File "C:\Users\arswe\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[**********************79%*************          ]  207 of 261 completed
Exception in thread Thread-218:
Traceback (most recent call last):
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 181, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\base.py", line 179, in history
    data = data.json()
  File "C:\Users\arswe\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[**********************92%*******************    ]  240 of 261 completed
Exception in thread Thread-253:
Traceback (most recent call last):
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\arswe\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\multi.py", line 181, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\arswe\anaconda3\lib\site-packages\yfinance\base.py", line 179, in history
    data = data.json()
  File "C:\Users\arswe\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arswe\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\arswe\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[**********************97%********************** ]  254 of 261 completed
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-2e002d24d240> in <module>
     26 
     27 now = dt.datetime.now()
---> 28 df = yf.download(tickers, '2019-01-01', now)['Adj Close']
     29 df.fillna(method='ffill', inplace=True)
     30 df

~\anaconda3\lib\site-packages\yfinance\multi.py in download(tickers, start, end, actions, threads, group_by, auto_adjust, back_adjust, progress, period, show_errors, interval, prepost, proxy, rounding, **kwargs)
     95                                    rounding=rounding)
     96         while len(shared._DFS) < len(tickers):
---> 97             _time.sleep(0.01)
     98 
     99     # download synchronously

KeyboardInterrupt: 
```

**Comment by Bertron01** [comment]
having this issue as well. First noticed it roughly 8 hours ago when I was trying to get intraday data from yesterday.

**Comment by echoyes** [comment]
same problem

**Comment by mberk** [comment]
Same here

**Comment by mberk** [comment]
Actually my problem was fixed by upgrading to the latest version (I was previously using 0.1.55)
