### ISSUE TITLE
No Exception passed when no Internet connection with Threaded requests

### ISSUE THREAD

**Issue by sityware** [ranaroussi/yfinance#927]
When using a threaded YFinance request, if there is no Internet connection the request hangs the program and you cannot catch the exception that is raised.
Using 0.1.68 latest.

Example:
Disconnect from the Internet and try the request below.

Workaround at the bottom - base.py

```
try:
     result = yf.download(tickers="AAPL", period="5d", interval="1d", group_by='column', auto_adjust=True, prepost=True, threads=True, proxy=None)
except:
     print("error")
```

Application hangs with this error in the console.

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\yfinance\base.py", line 208, in history
    if "chart" in data and data["chart"]["error"]:
UnboundLocalError: local variable 'data' referenced before assignment
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\yfinance\base.py", line 208, in history
    if "chart" in data and data["chart"]["error"]:
UnboundLocalError: local variable 'data' referenced before assignment

Process finished with exit code -1
```

I have edited base.by with a workaround. I'm not sure if this is the right way but I can work with it from my application.
Try and Pass the exception

```
        try:
            err_msg = "No data found for this date range, symbol may be delisted"
            if "chart" in data and data["chart"]["error"]:
                err_msg = data["chart"]["error"]["description"]
                shared._DFS[self.ticker] = utils.empty_df()
                shared._ERRORS[self.ticker] = err_msg
                if "many" not in kwargs and debug_mode:
                    print('- %s: %s' % (self.ticker, err_msg))
                return shared._DFS[self.ticker]

            elif "chart" not in data or data["chart"]["result"] is None or \
                    not data["chart"]["result"]:
                shared._DFS[self.ticker] = utils.empty_df()
                shared._ERRORS[self.ticker] = err_msg
                if "many" not in kwargs and debug_mode:
                    print('- %s: %s' % (self.ticker, err_msg))
                return shared._DFS[self.ticker]
        except Exception:
            pass
```

**Comment by sityware** [comment]
#920 already resolved.
