### ISSUE TITLE
pandas-1.4 yfinance-0.1.69 AttributeError: 'Index' object has no attribute 'tz_localize'

### ISSUE THREAD

**Issue by peterxie1** [ranaroussi/yfinance#939]
Just upgraded to yfinance-0.1.69 and pandas-1.4 you will likely hit this issue. The code is trivial and used to work fine. Any suggestions?

python-3.9.10
windows 10

> python
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
>>> yf.__version__
'0.1.69'
>>> ticker = "QQQ"
>>> period = "1d"
>>> interval = "5m"
>>> print(ticker, period, interval)
QQQ 1d 5m
>>> yf.download([ticker], period=period, interval=interval)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\base.py", line 295, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\yfinance\multi.py", line 112, in download
    _time.sleep(0.01)
KeyboardInterrupt
>>>

**Comment by tsdeng** [comment]
lol, just saw the same problem and spent an hour debugging.
It happens with pandas version 1.4 which is just released yesterday.
To workaround it, you can install `pip install pandas==1.3.5`.
But yeah, it's a problem that needs a fix when using pandas 1.4

**Comment by peterxie1** [comment]
Thanks for the note! yes, downgrading pandas from 1.4 to 1.3.5 worked-around this issue.

**Comment by wonka929** [comment]
yes, same issue here!

**Comment by nichmetsa** [comment]
same issue here

**Comment by Hooregi** [comment]
same here, had to roll back the pandas version

**Comment by ysdede** [comment]
🖐

**Comment by ysdede** [comment]
> lol, just saw the same problem and spent an hour debugging. It happens with pandas version 1.4 which is just released yesterday. To workaround it, you can install `pip install pandas==1.3.5`. But yeah, it's a problem that needs a fix when using pandas 1.4

Thanks!

**Comment by Rational-IM** [comment]
I also tried downgrading yfinance to older versions - it didn't work. There were other changes on pandas 1.4 that required some adjustments on other parts of my code - maybe this update is a broader one.

**Comment by mundus08** [comment]
I faced the same problem.  It might be related to pandas change:
"Ignoring dtypes in concat with empty or all-NA columns"
The problem seams to in 
        df = _pd.concat([quotes, dividends, splits], axis=1, sort=True)

df.intext.dtype=object in pandas 1.4 because dividends and splits are empty.
With pandas 1.3.5 df.intext.dtype=datetime64[ns]

**Comment by Dharmik-19** [comment]
> 
Hi @mundus08 , I am a newbie in the deployment domain. I was curious how you find the exact lines which might be the solution to the problem we are facing. So, did you go through the entire code for pandas to find the prospective lines which can be causing the trouble?

**Comment by mundus08** [comment]
Hi @Dharmik-19 
the stack trace contained the line number where the problem occured in yfinance. Then I added some print statements to the code and found out that the index dtype has changed. I suspected that it was due to the concat statement (because the dtype of the quotes df was still correct). In the release notes of pandas 1.4 I found a reference to the changes in the concat method.

**Comment by ProgrammingDao** [comment]
Duplicates of https://github.com/ranaroussi/yfinance/issues/937 I believe.

**Comment by Rational-IM** [comment]
Although #937 was closed, I still get an error message after updating Python/Pandas. I run the file test_yfinance.py and here are the results:

runfile('C:/Users/danil/OneDrive/Python_projects/RIM_trading/untitled0.py', wdir='C:/Users/danil/OneDrive/Python_projects/RIM_trading', current_namespace=True)
Reloaded modules: rim_functions_library, Odysseus_calc, Odysseus_port, Odysseus_trade, Odysseus_charts, Odysseus_data
E.E
======================================================================
ERROR: test_attributes (__main__.TestTicker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\danil\OneDrive\Python_projects\RIM_trading\untitled0.py", line 44, in test_attributes
    ticker.dividends
  File "C:\Users\danil\anaconda3\envs\spyder-5.2.2\lib\site-packages\yfinance\ticker.py", line 131, in dividends
    return self.get_dividends()
  File "C:\Users\danil\anaconda3\envs\spyder-5.2.2\lib\site-packages\yfinance\base.py", line 692, in get_dividends
    self.history(period="max", proxy=proxy)
  File "C:\Users\danil\anaconda3\envs\spyder-5.2.2\lib\site-packages\yfinance\base.py", line 295, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

======================================================================
ERROR: test_info_history (__main__.TestTicker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\danil\OneDrive\Python_projects\RIM_trading\untitled0.py", line 35, in test_info_history
    history = ticker.history(period="max")
  File "C:\Users\danil\anaconda3\envs\spyder-5.2.2\lib\site-packages\yfinance\base.py", line 295, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

----------------------------------------------------------------------
Ran 3 tests in 20.653s

FAILED (errors=2)

**Comment by neilsmurphy** [comment]
Confirm downgrading to pandas 1.3.5 solved the issue.

**Comment by grzesir** [comment]
any updates on a fix?

**Comment by hubbubba** [comment]
The pandas downgrade worked for me as well. I'm looking forward to a fix for 1.4x.

**Comment by ValueRaider** [comment]
I'm willing to fix but can't reproduce, so I need your help to debug. Run this for me and paste the output:
```
df = yf.download("QQQ", interval="5m", period="1d")
try:
 print(type(df.index))
 print(df.index[0])
 print(type(df.index[0]))
 print(df.index[0].tzinfo)
 print(type(df.index[0].tzinfo))
except:
 pass
```

**Comment by ValueRaider** [comment]
Does this still happen in the latest release?

**Comment by waqaskhan137** [comment]
For me it was still causing the issue even after install panadas 1.3.5
But then I printed the version and came to know it wasnt using pandas 1.3.5 I had to restart the kernal of jupyter notebook in order to get the defined version. 

![image](https://user-images.githubusercontent.com/4752256/198928196-51010524-2684-426d-b4a0-514d90af23ff.png)

```
!pip install yfinance
!pip install -U pandas==1.3.5

import yfinance as yf
import pandas as pd
import sys
 
 
print("Python Version", sys.version)
print("Yahoo Fianance lib : ", yf.__version__)
print("Panadas : ", pd.__version__)
```
Python Version 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
Yahoo Finance  :  0.1.67
Panadas :  1.5.1

**Comment by wgong** [comment]
Thank you, `pandas==1.3.5` worked

**Comment by wgong** [comment]
@ValueRaider I just upgraded pandas back to 1.5.1, and cannot reproduced it either.

Here is my function which failed before
```
def gwg_download_yf(tickers, start_dt, end_dt=""):
    """download quotes of multiple tickers for given start_dt, end_dt (exclusive)
    Args:
        tickers (list)
        start_dt (str) - YYYYMMDD
        end_dt (str) - YYYYMMDD, optional. If end_dt = "", will download one date at start_dt
        
    Returns:
        dataframe or None
    """    
    df_ = None
    if len(tickers) < 1:
        return df_
    
    start_date = datetime.strptime(start_dt, "%Y%m%d")
    if not end_dt:
        end_date = start_date + timedelta(days=1)
    else:
        end_date = datetime.strptime(end_dt, "%Y%m%d")
    data = yf.download(" ".join(tickers), 
                    start=datetime.strftime(start_date, "%Y-%m-%d"), 
                    end=datetime.strftime(end_date, "%Y-%m-%d"))
    return data
```

**Comment by wgong** [comment]
@ValueRaider  I tried on a different Ubuntu computer, and cannot reproduce the initial error.

**Comment by AminatAzeez** [comment]
I downgraded to 1.3.5 and restarted the kernel but I am still getting the same error

AttributeError                            Traceback (most recent call last)
Input In [10], in <cell line: 3>()
      1 #Question 3 Obtain stock data for AMD using the history function, set the period to max. 
      2 #Find the Volume traded on the first day (first row).
----> 3 amd_stock_data = amd.history(period="max")

File ~\anaconda3\lib\site-packages\yfinance\base.py:279, in TickerBase.history(self, period, interval, start, end, prepost, actions, auto_adjust, back_adjust, proxy, rounding, tz, timeout, **kwargs)
    276 df["Stock Splits"].fillna(0, inplace=True)
    278 # index eod/intraday
--> 279 df.index = df.index.tz_localize("UTC").tz_convert(
    280     data["chart"]["result"][0]["meta"]["exchangeTimezoneName"])
    282 if params["interval"][-1] == "m":
    283     df.index.name = "Datetime"

AttributeError: 'Index' object has no attribute 'tz_localize'

please help....

**Comment by ValueRaider** [comment]
That looks like old code. Update yfinance to latest version, confirm with `import yfinance as yf ; print(yf.__version__)`

**Comment by AminatAzeez** [comment]
I checked version and it says 0.1.67

**Comment by AminatAzeez** [comment]
It works fine now, I just realized the version of the pandas was not changing , I was installing it the wrong way. So, I got the correct installation and it worked

**Comment by iamNeverwell** [comment]
Restarted Kernel;

!pip install yfinance
!pip install -U pandas==1.3.5

Confirmed

**Comment by ValueRaider** [comment]
> Confirmed

Confirmed what?

Also everyone should be able to use any version of Pandas >=1.3.0 without problems.

**Comment by Abdul675** [comment]
In my case downgrading the pandas version to 1.3.5 is not working same error how can i resolve this

**Comment by waqaskhan137** [comment]
> For me it was still causing the issue even after install panadas 1.3.5 But then I printed the version and came to know it wasnt using pandas 1.3.5 I had to restart the kernal of jupyter notebook in order to get the defined version. Hope this will help someone who is facing the similar issue.
> 
> ![image](https://user-images.githubusercontent.com/4752256/198928196-51010524-2684-426d-b4a0-514d90af23ff.png)
> 
> ```
> !pip install yfinance
> !pip install -U pandas==1.3.5
> 
> import yfinance as yf
> import pandas as pd
> import sys
>  
>  
> print("Python Version", sys.version)
> print("Yahoo Fianance lib : ", yf.__version__)
> print("Panadas : ", pd.__version__)
> ```
> 
> Python Version 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] Yahoo Finance : 0.1.67 Panadas : 1.5.1

@Abdul675  please refer to this

**Comment by ValueRaider** [comment]
@waqaskhan137 Please don't recommend downgrading, this issue needs to be debugged and fixed.

@Abdul675 Try branch `fix/prices-index-not-datetime` (instructions #1080) and give feedback.

**Comment by ValueRaider** [comment]
Is this fixed in latest release 0.2.17?

**Comment by kaili-yang** [comment]
same issue here

**Comment by ValueRaider** [comment]
@kaili-yang Create a new issue following its instructions.

**Comment by MrEriikR** [comment]
It worked for me by using the code `!pip install pandas==1.3.5` and t hen restarting the kernel.
