### ISSUE TITLE
Prevent panda to print stack trace

### ISSUE THREAD

**Issue by sasadangelo** [ranaroussi/yfinance#98]
Hi,

I have an ETF on the Italian market that I think it is delisted. I have a code like this:

```
import datetime as dt
import pandas as pd
import fix_yahoo_finance as yf
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as web
yf.pdr_override()

start_date = dt.datetime(2018, 10, 10)
end_date = dt.datetime.now()

try:
    df = web.get_data_yahoo("XEZD.MI", start_date, end_date)
except:
    print("Error")
```

When I run it I got the following exception:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fix_yahoo_finance/__init__.py", line 250, in history
    quotes = self._parse_quotes(data["chart"]["result"][0])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fix_yahoo_finance/__init__.py", line 109, in _parse_quotes
    timestamps = data["timestamp"]
KeyError: 'timestamp'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fix_yahoo_finance/__init__.py", line 317, in _download_one_threaded
    period, interval, prepost)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fix_yahoo_finance/__init__.py", line 328, in _download_one

```

In the beginning, I thought it was raised by your library. But later I noticed the catch clause is not activated, in fact, your API return normally. I noticed the error appeared when I introduced the lines:

```
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as web
```

If you remove them the exception is regularly caught. This stuff confuses me. I am not a Python expert. I don't understand how I can reference web here:

```df = web.get_data_yahoo("XEZD.MI", start_date, end_date)```

if I don't import it. The code snippet I posted here is part of a bigger program where the same python3 force me to declare web in the import statement. This is the reason why I need the code snippet works fine with all the three import above defined.
Another thing that confuses me is why if I specify it the stack trace is printed.

PS
I upgraded yfinance to the latest version and I also tried to use the import below, but same result.

```
import yfinance as yf
```

**Comment by sasadangelo** [comment]
Anyone can help?

**Comment by ranaroussi** [comment]
Issue was fixed in 0.1.46. Errors are printed after all the downloads complete.

**Comment by sasadangelo** [comment]
Hi,
The fix works but in my opinion, it is not correct. Let me elaborate.
Now a message like this appears:

1 Failed download:
- SP5EUY.MI: No data found for this date range, the symbol may be delisted

The problem is that you decide to print something on the screen but you are not aware of the author of the program that use your library wants this. In my case, I don't want that print. I want an exception to catch and decide whether to print something or not.

**Comment by samirelanduk** [comment]
I agree - it would make more sense to have an option not to print out. For example if you are using a tqdm progress bar to request multiple symbols in succession, it breaks the bar every time there is missing data.
